### ISSUE TITLE
Error when there is no executable code

### ISSUE THREAD

**Issue by moepwintphyu1996** [End-to-end-provenance/RDataTracker#100]
When the user tries to run a file with no executable code in it, the error message will show as 

[1] "Error in if (!is.na(df$pnum[i - 1]) & !is.na(df$pnum[i]) & df$pnum[i - : argument is of length zero\n"
Error in if (pname == script.name) { : argument is of length zero
In addition: Warning message:
In .ddg.insert.error.message(error.msg) :
 No binding for .ddg.source.parsed . DDG may be incorrect!

Error in if (as.numeric(snum) > 0) line <- paste(snum, ":", lnum, sep = "") else line <- lnum : 
argument is of length zero

**Comment by MKLau** [comment]
I think this has been addressed. Using ddg.run with a file that doesn't contain executable code now runs normally, generating output. Attempting to start DDG Explorer with ddg.display returns "Unable to start DDG Explorer: Null"
