### ISSUE TITLE
Function Processing Error from RDataTracker

### ISSUE THREAD

**Issue by moepwintphyu1996** [End-to-end-provenance/RDataTracker#106]
I was trying to run the script below

```
f <- function(x) {
  r <- x - g(x)
  r
}

g <- function(y) {
  r <- 3
  r
}

f(4)

```

and it produces the error 
```
"Error in last.statement[1]: object of type 'symbol' is not subsettable\n"
```

**Comment by MKLau** [comment]
Hey Moe, I just ran that and it returned 1, as would be expected. Try clearing your objects with rm(list=ls())

**Comment by erboose** [comment]
I tracked this down to a problem with the function annotation code but it should be easy to fix.

Sent from my iPhone

On Jun 4, 2016, at 11:54 AM, MKLau <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Moe, I just ran that and it returned 1, as would be expected. Try clearing your objects with rm(list=ls())

-

**Comment by erboose** [comment]
Fixed and closed.
