### ISSUE TITLE
install error on windows fresh install RStudio via github

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#115]
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringi'

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'magrittr'

Work around:
install.packages("stringi",type="win.binary")
install.packages("magrittr",type="win.binary")

Then run: devtools::install_github('blernermhc/RDataTracker')

See: http://stackoverflow.com/questions/31038636/package-stringi-does-not-work-after-updating-to-r3-2-1

**Comment by erboose** [comment]
Still no joy.  Used modified install command:

     devtools::install_github('End-to-end-provenance/RDataTracker', ref='development', force=TRUE)

but ddg.run continues to crash in RStudio.

**Comment by tfjmp** [comment]
Yep same here, trying to get to the root cause.

**Comment by tfjmp** [comment]
Open issue for the crash: https://github.com/End-to-end-provenance/RDataTracker/issues/116

Don't think installation problem is directly related.

**Comment by tfjmp** [comment]
For Barbara, I don't know why there is a dependency, but there is one.
