### ISSUE TITLE
Software dependencies for development

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#118]
Hi,

They need to be listed, and ideally installed through a script on all platform.

So far what it is missing when starting to dev (on Windows at least, diff probably be there on a Linux machine):
ant
diff (for test-no-instrumentation.xml)

There maybe others. Ideally we want anyone to be able to clone the repo, go through a documented installation process (or launch a script) and start to develop straight away.

**Comment by tfjmp** [comment]
Also see issue #33.

**Comment by tfjmp** [comment]
Also see issue #131.

**Comment by blernermhc** [comment]
We should check our Readme and make sure it points to the github repo.  In the repo, we should have documentation to help a developer get started.
