### ISSUE TITLE
If script doesn't end in new line, warning message from RDataTracker

### ISSUE THREAD

**Issue by alexsiqingliu** [End-to-end-provenance/RDataTracker#119]
Warning message:
In readLines(script.file) : incomplete final line found on 'relative.R'

**Comment by fong22e** [comment]
I have not seen this error in a long time. I used `ddg.run` on a few R scripts that do not contain an additional line at the end of the script file and this error does not show up.

**Comment by MKLau** [comment]
Hi Elizabeth, thanks for testing this. Which script did you use? Let me know and I'll test on my Mac and maybe we can close this issue.

**Comment by fong22e** [comment]
Hi Matt, I used the code found in [Issue 135](https://github.com/End-to-end-provenance/RDataTracker/issues/135). Thank you so much!

@MKLau

**Comment by MKLau** [comment]
Hi Elizabeth, I just realized that readLines will always display this warning if there is not an EOL on the final line. See the stackoverflow thread below, but it is possible to turn off this warning, which it's possible that Alex or someone else might have done. 

http://stackoverflow.com/questions/5990654/incomplete-final-line-warning-when-trying-to-read-a-csv-file-into-r#5996412

**Comment by erboose** [comment]
Right.  When an R script is executed with ddg.run, the script file is read in by ddg.source using readLines (warn=FALSE).  It's possible the warn parameter was missing in earlier versions of ddg.source.

**Comment by fong22e** [comment]
Thank you so very much!
