### ISSUE TITLE
RMarkdown test does not pass currently

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#124]
After merging the installed packages changes in with the previous updates dealing with breakpoints and relative paths, the RMarkdown test stopped working.

Instead of just creating a ddg folder, it is also creating an RMarkdown_ddg folder.  It is placing the R script that is created by processing the Rmd file into the RMarkdown_ddg folder, but later RDataTracker code is looking for that file in the ddg directory.

When running regression tests, we expect the ddg folder to be used.  There should be no RMarkdown_ddg folder.

**Comment by erboose** [comment]
This problem appears to be solved with recent commit to development.
