### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by margoseltzer** [End-to-end-provenance/RDataTracker#126]
As I'm preparing the data for the tutorial, I find that having to scroll through the DDG directory through  a large number of files is tedious and distracting when what I want to do is go directly to the DDG.  I wonder if it might make sense to structure the ddg directory a bit more.

I was thinking that we could place the following in the DDG directory:
annotated-script.r
ddg.json
ddg.txt
dflow.txt
dnodes.txt
dobjects.csv
inenv.txt
pnodes.txt
returns.txt
sourced-scripts.txt

and then create a subdirectory "datafiles' (in the DDG directory) and place everything else in there -- some of the names of nodes are quite long and I find that both in a browser and in ls, they get in the way.

Thoughts?

- M

**Comment by erboose** [comment]
The current version of RDataTracker in development has an option in ddg.run (display=TRUE) provided by Moe that will automatically start DDG Explorer and display the DDG when the script completes execution. This removes the need to find ddg.txt and the jar file for DDG Explorer.

**Comment by margoseltzer** [comment]
As we save DDGs, then we must be assuming that users might want to view them at times other than when they’ve just completed a run, so while this feature is terrific, I don’t think it really addresses the fundamental issue - if DDGs persist because we expect people to want them, then it would be nice to make it really easy to find them/see them.

- M

**Comment by erboose** [comment]
Good point. A separate directory for data files makes sense. This would need to be implemented in both RDataTracker and DDG Explorer.

**Comment by blernermhc** [comment]
I don't think this should involve a change to DDGExplorer.  If RDataTracker includes the directory name as part of the filename in the nodes, that should suffice for DDGExplorer to be able to find them.

**Comment by erboose** [comment]
Following up on this suggestion, I've created a version of RDT that adds some organization to the ddg directory.  For example, if the script name is "test.r":

./test_ddg contains ddg.txt and ddg.json
./test_ddg/data contains the numbered snapshot files that store intermediate data
./test_ddg/debug contains dumps of lookup tables (data nodes, etc) for troubleshooting
./test_ddg/scripts contains various R scripts.

The last includes the original R script, sourced scripts (if any), the original Rmd script and derivative R script (for markdown files), annotated-script.r (for function annotations), and modified scripts used to set breakpoints (if any).

Comments and suggestions welcome.

Emery

**Comment by margoseltzer** [comment]
This sounds great!

- M

**Comment by tfjmp** [comment]
May I suggest .ddg/test/.... rather than ./test_ddg
(if ./ is [...]/.ddg, ddg is then redundant)
My rational is that it will be nice to have all ddg output together in the same "main" directory.

**Comment by erboose** [comment]
Right, that would be a logical choice. The current default, which creates a sub-directory under the script directory, also works well for users who gather their scripts in one place.

Here I was more interested in what the sub-directories should be and where the individual files should go. It would be easy enough to reassign the main ddg directory once we have a consensus on what it should be.  Or to make it configurable by the user.

**Comment by erboose** [comment]
Subdirectories and file organization implemented as noted above.
