### ISSUE TITLE
ant build fails due to tex problem

### ISSUE THREAD

**Issue by margoseltzer** [End-to-end-provenance/RDataTracker#131]
I was trying to build the distribution from the repository and was unable to get a tar.gz, because the ant build option builds documentation and needs something called supertabular.sty, which I didn't have. It seems that having this coupling might not be ideal.

**Comment by erboose** [comment]
The current ant build creates PDFs of the two instruction manuals.  As we move toward online documentation and tutorials, it might make sense to remove this feature since it takes time and requires special software.  It’s also hard to keep the manuals up to date.

**Comment by erboose** [comment]
This feature was removed in the regression branch.
