### ISSUE TITLE
Two copies of DDG showing up in ddg.txt

### ISSUE THREAD

**Issue by margoseltzer** [End-to-end-provenance/RDataTracker#132]
I am attaching a zip containing a script dummy.r and a datafile data_v2.csv that cause RDataTracker to place two copies of a DDG in the ddg.txt file. 
[doubleddgbug.zip](https://github.com/End-to-end-provenance/RDataTracker/files/356288/doubleddgbug.zip)

As shown in the "make_groups" function, everything works just fine if we invoke the payoff function on any particular column of the data, but if we call payoff on the difference of two of the columns, then we generate the failure.

RDataTracker reports a bunch of warnings:

Warning messages:
1: In .ddg.insert.error.message("Source code line numbers may be incorrect 2") :
 Source code line numbers may be incorrect 2
2: In .ddg.insert.error.message("Source code line numbers may be incorrect 2") :
 Source code line numbers may be incorrect 2
3: In if (pname == script.name) { ... :
 the condition has length > 1 and only the first element will be used
4: In ddg.proc.nodes$ddg.name[ddg.pnum] <- pname :
 number of items to replace is not a multiple of replacement length
5: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
6: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
7: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
8: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
9: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
10: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used
11: In if (.ddg.is.proc.node(type) & ddg.proc.nodes$ddg.name[i] ==  ... :
 the condition has length > 1 and only the first element will be used

And then the display crashes with:
> ddg.run("dummy.r", display=TRUE);
[1] "Saving ddg.txt in ./dummy_ddg"
[1] "Saving ddg.json in ./dummy_ddg"
laser.ddg.ParameterAlreadyBoundException: Parameter already bound:  1-institutionsText
	at laser.ddg.AbstractProcedureInstanceNode.addOutput(AbstractProcedureInstanceNode.java:267)
	at laser.ddg.DDGBuilder.addDataProducer(DDGBuilder.java:120)
	at laser.ddg.persist.Parser.parseDataFlowEdge(Parser.java:914)
	at laser.ddg.persist.Parser.parseEdge(Parser.java:862)
	at laser.ddg.persist.Parser.addEdges(Parser.java:835)
	at laser.ddg.persist.Parser.addNodesAndEdges(Parser.java:191)
	at laser.ddg.commands.LoadFileCommand.loadFile(LoadFileCommand.java:62)
	at laser.ddg.commands.LoadFileCommand.loadDDG(LoadFileCommand.java:45)
	at laser.ddg.gui.DDGExplorer.main(DDGExplorer.java:551)
There were 50 or more warnings (use warnings() to see the first 50)
> 

If I use ddg.init()/ddg.save() and manually enter:

origdata=read.csv("data_v2.csv");
D = origdata
r = merge(aggregate(D[,c("numInGroup","Chat","Institution","Truth","InitialEstimate",paste("Estimate",1:10,sep=""),"Decision","GroupDecision")],list(runID=D$runID),median),aggregate(D[,c("Pay","Certainty1","Certainty2")],list(runID=D$runID),mean))
r[r$Institution==0,"FinalPerformance"] =
            payoff(abs(r[r$Institution==0,"Decision"] - r[r$Institution==0,"Truth"]));

everything works just fine!

**Comment by blernermhc** [comment]
Obviously, we need to fix this, but as a workaround, you can assign the expression you are passing to payoff to a variable and then just pass the variable.  This will eliminate the errors you are seeing.
```
diff = abs(r[r$Institution==0,"Decision"] - r[r$Institution==0,"Truth"])
r[r$Institution==0,"FinalPerformance"] = payoff(diff);
```
