### ISSUE TITLE
Invalid JSON in ddg.json

### ISSUE THREAD

**Issue by pdurbin** [End-to-end-provenance/RDataTracker#133]
I just ran `ddg.run(“eeProvCalculateSquare.R”)` as part of https://github.com/End-to-end-provenance/RDataTracker/wiki/eeProv-Guided-Tutorial and ddg.json was produced but it's not valid JSON. Removing a trailing comma near the end of ddg.json made it pass a JSON validator.

**Comment by blernermhc** [comment]
Is this fixed?

**Comment by pdurbin** [comment]
@blernermhc I hope so! 😄
