### ISSUE TITLE
DDG created differently if code is in a function

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#135]
The DDG that is created by code at the top-level and identical code placed inside a function is not always the same.  Here is an example where they differ.  Notice the input edges to the nodes that are updating bu.

```
bu.url <- "http://harvardforest.fas.harvard.edu/sites/harvardforest.fas.harvard.edu/files/eeprov/bigelow-upper.dat"

bu.file <- file(bu.url)

bu <- read.csv(bu.file, header=FALSE, col.names=c("table","year","jd","time","sec","bu.stg","bu.wt","bu.wt2"))

# get date
bu$date <- as.Date(bu$jd - 1, origin=paste(bu$year, "-01-01", sep=""))
# convert date to character
bu$date <- as.character(bu$date)

update.bu <- function() {
  bu.file <- file(bu.url)
  bu <<- read.csv(bu.file, header=FALSE, col.names=c("table","year","jd","time","sec","bu.stg","bu.wt","bu.wt2"))


  # get date
  bu$date <<- as.Date(bu$jd - 1, origin=paste(bu$year, "-01-01", sep=""))
  # convert date to character
  bu$date <<- as.character(bu$date)
}

update.bu()
```

<img width="425" alt="missinginedges" src="https://cloud.githubusercontent.com/assets/5429878/16818079/e7c5c598-4913-11e6-97c6-c2d89f756c90.png">

**Comment by fong22e** [comment]
When I ran the above code using `ddg.run`, this is the ddg that I got. It looks to me like the ddg generated for the code inside the function is now the same as the ddg generated for the code outside the function.

![test](https://cloud.githubusercontent.com/assets/20979904/21418193/65a6dcc4-c7ed-11e6-9eba-626a5fec0592.png)
