### ISSUE TITLE
Missing relationship?

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#137]
I am playing around with the graph generated from the JSON of the self-guided tutorial. It works pretty well. However, I think there is some missing relationship. I am looking at the final .jpeg being generated. I am ignoring control flow as I wish to understand from which dataset a certain data was built. It mostly works fine, except for a few potential "problem"(?).
## I first select a node corresponding to one of the figure:

![datadep2](https://cloud.githubusercontent.com/assets/1970355/16843783/b1bd10e4-49b0-11e6-8f62-3c36d71ee7a7.png)
## It works pretty well:

![datadep1](https://cloud.githubusercontent.com/assets/1970355/16843860/e860d39c-49b0-11e6-8a78-37d59735c7db.png)
## I can trace it back to a given csv file:

![datadep3](https://cloud.githubusercontent.com/assets/1970355/16843875/f318f9f4-49b0-11e6-8660-27644b8e7677.png)
## However, when looking at the jpeg, it has no data dependencies:

![image](https://cloud.githubusercontent.com/assets/1970355/16843917/16558a54-49b1-11e6-9cd8-cef598feba4e.png)

Following the Prov standard, the jpeg could be either defined as a `dictionary` containing the figures (connected by `hadDictionaryMember` relations) or the activity connected to the jpeg node should be connected to the individual figures by `used` relations (the last one is more in line with how RDataTracker seems to work).

**Comment by tfjmp** [comment]
Other issue:

## Here only one node seems to dependent from stud4[...].csv

![image](https://cloud.githubusercontent.com/assets/1970355/16845540/4c51e610-49b7-11e6-8658-eefcf46ab667.png)

## But it is actually separate version of s4, that are not connected by any form of relationship:
![image](https://cloud.githubusercontent.com/assets/1970355/16845616/8b467ea8-49b7-11e6-9ed3-07bcede70fa2.png)

**Comment by blernermhc** [comment]
ggplot is not supported yet.

**Comment by blernermhc** [comment]
ggplot2 is now supported in https://github.com/End-to-end-provenance/RDataTracker/commit/f4c1445c87b17b7a6ceb32ea3e58aa253a1ad163
