### ISSUE TITLE
R Package as independent nodes.

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#138]
I am thinking of separating R packages from the environment node as independent node.

We may also want, later, to connect activity to their corresponding package. If there is a bug in a given package we could identify  impacted output if several.

**Comment by blernermhc** [comment]
Sorry, I don't understand what this means.  Can you explain?

**Comment by tfjmp** [comment]
Right now packages are attributes of the environment node in the JSON file. I want to pop them out as nodes in the provenance graph.

**Comment by margoseltzer** [comment]
This seems like a truly valuable thing we could provide. If the graph showed what values were derived from particular packages, then someone could use the DDG to consider/decide/determine if it's important to upgrade to the latest release of a library or to decide whether a change of library version could be contributing to a difference in result.

**Comment by erboose** [comment]
Agreed. To do this for a particular value, we'd need to be able to examine its derivation history and look for calls to functions from installed packages. Perhaps return a list of functions called with corresponding package name and version number.

Sent from my iPhone

On Jul 14, 2016, at 4:29 PM, margoseltzer <notifications@github.com<mailto:notifications@github.com>> wrote:


This seems like a truly valuable thing we could provide. If the graph showed what values were derived from particular packages, then someone could use the DDG to consider/decide/determine if it's important to upgrade to the latest release of a library or to decide whether a change of library version could be contributing to a difference in result.

-

**Comment by tfjmp** [comment]
Need to revisit this.

**Comment by fong22e** [comment]
It looks like we have to separate out packages from the environment node to make it PROV-JSON compliant.
