### ISSUE TITLE
No Edge to Self-Referencing Node

### ISSUE THREAD

**Issue by alexsiqingliu** [End-to-end-provenance/RDataTracker#150]
When an object references itself in an assignment, the corresponding edge is not created. An example below:

```
z <- 2
z <- z*2
```

Produces this DDG:
![image](https://cloud.githubusercontent.com/assets/19556612/17188151/e7780082-5409-11e6-8862-59119a000633.png)

An edge should be drawn from 1-z to 2-z

**Comment by fong22e** [comment]
For the following case:
```
a <- 5
a <- a + 5
```
This is the DDG produced. I am running this on the code from the development branch.
![test](https://cloud.githubusercontent.com/assets/20979904/21364823/75dbeb58-c6c0-11e6-8b9c-e4b673cbf7ff.jpg)

**Comment by blernermhc** [comment]
This is working now.  I do not know in which commit it was fixed.

**Comment by erboose** [comment]
Fixed in control2 branch.  See comment in .ddg.create.data.use.edges.for.console.cmd in RDataTracker.R.
