### ISSUE TITLE
Error linked to "trycatch" of last, fully executable function instead of function producing the error

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#155]
This is not a bug, but an un-intuitive feature. The "trycatch" does link to the correct line the produces the error via a right-click and click "show code" in DDG-Explorer, which is informative. 

It would be great if the graph itself reflected the connection between the error and the actual function call that generated the error. 

This would make the error and its relation to the other nodes (i.e. the data generating the error) immediately visible in the graph (i.e. as opposed to "trycatch", which is not a function associated with the script itself).

@blernermhc @margoseltzer @moepwintphyu1996 @tfjmp @erboose

**Comment by MKLau** [comment]
![screen shot 2016-09-19 at 1 59 24 pm](https://cloud.githubusercontent.com/assets/5342857/18643193/fce5f9a0-7e71-11e6-81ce-fd4f8b2132cf.png)


![screen shot 2016-09-19 at 9 50 32 am](https://cloud.githubusercontent.com/assets/5342857/18643175/ec1086fe-7e71-11e6-82ee-5ca3a572334c.png)

**Comment by MKLau** [comment]
Camflow/cytoscape visualizer doesn't make the connection to the error generating function at all. @tfjmp 

![download](https://cloud.githubusercontent.com/assets/5342857/18643632/02aaa2f8-7e74-11e6-8286-10855ffa3858.png)
![download-1](https://cloud.githubusercontent.com/assets/5342857/18643635/0515faba-7e74-11e6-84bc-8821d29c8a29.png)

**Comment by tfjmp** [comment]
I am not sure I see the difference between DDG-Explorer, they both seem to connect the error.msg to the try catch which itself connect to apply(x1x2, 2, sum) (though not sure why the line numbers are different).

**Comment by MKLau** [comment]
Structurally, they're the same, but I didn't see that cytoscape provides the line number. In DDG-Exp, when you right click trycatch it brings up a rendering of the original script with the line-number highlighted. But I just found the line number is the cytoscape right click info.


@tfjmp
