### ISSUE TITLE
Add option to save debug files

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#156]
When a script is executed with ddg.run, several files are currently written to the debug directory to support trouble shooting.  A parameter (e.g. save.debug) might be added to ddg.run and ddg.save to optionally save these files when they are needed.  A copy of the annotated script (not currently saved) should be included.

**Comment by blernermhc** [comment]
Done in [https://github.com/End-to-end-provenance/RDataTracker/commit/6baad08391e377535d9d05b549f38ec62d45191d](https://github.com/End-to-end-provenance/RDataTracker/commit/6baad08391e377535d9d05b549f38ec62d45191d)
