### ISSUE TITLE
The internals of environments are not visible in the resulting ddg

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#160]
When the following code is run using RDataTracker, the resulting ddg does not display the internal variables of the environment.

```
env1 <- new.env()
env1$a <- 1
```

The generated JSON file is attached as a .txt file below as GitHub does not support .json files.
[ddg.json.txt](https://github.com/End-to-end-provenance/RDataTracker/files/497519/ddg.json.txt)

**Comment by blernermhc** [comment]
Implemented in https://github.com/End-to-end-provenance/RDataTracker/pull/559/commits/9ec6ccedff34586b2a603573c70d7ff272da9e8a

The provenance now lists the names of the variables contained within an environment.
