### ISSUE TITLE
tfjmp fork issue

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#164]
In `[<-`(`*tmp*`, next.cmd, value = <S4 object of class structure("DDGStatement", package = "RDataTracker")>) :                                                              
   implicit list embedding of S4 objects is deprecated

@tfjmp 

Hey, I got this error message when I ran your forked development branch version on a script of mine. If you need it, the script is in dev/src/eepOdy/src/eepOdy.R

**Comment by tfjmp** [comment]
warning or error? Does same thing with main repo development branch?

**Comment by MKLau** [comment]
It's a warning. It still generates a ddg. 

I haven't tried with the main repo yet.

**Comment by MKLau** [comment]
Just tried with the main repo development branch and got the same warning
