### ISSUE TITLE
Cleaning RDataTracker package content, features and branches

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#182]
Prioritizing bug-fixes and enhancement features along with the branches associated with them.

Also removing un-necessary files to decrease clutter and overall package size.

A zipped backup of the current state of the package (RDataTracker-master-11Nov2016.zip) is now in Dropbox/HarvardForest/RDataTracker.

**Comment by tfjmp** [comment]
See here: https://github.com/End-to-end-provenance/RDataTracker/branches

First pass through maybe to simply delete merged branch (I don't expect objection here). Next step would be to grow through stale branches (https://github.com/End-to-end-provenance/RDataTracker/branches/stale). We may need to discuss a bit more here, and decide what can safely be abandoned. Some branches are hundreds of commit behind. Maybe the person that last updated the branch could decide.
