### ISSUE TITLE
Operating system in environment, a bit too vague

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#184]
```
rdt:operatingSystem="unix"
```

Ideally replace this by the output of `uname -a` or equivalent.

**Comment by blernermhc** [comment]
In general, we should be checking what other computing environment information is available that we should be recording in the JSON.

**Comment by blernermhc** [comment]
See also issue #90

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/6dfb509eff98875032cdcc5957f7da7f97292675
