### ISSUE TITLE
CamFlow Error message in R

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#199]
![screen shot 2016-12-19 at 2 49 36 pm](https://cloud.githubusercontent.com/assets/5342857/21326899/a1b85872-c5fa-11e6-8fc5-1fa3fa88397a.png)

**Comment by MKLau** [comment]
Hey, I don't know if this is the same issue that Elizabeth was having, but, this is the current version of master.

**Comment by MKLau** [comment]
Hey Elizabeth, is this the error message that you were talking about?

@fong22e

**Comment by fong22e** [comment]
Hi Matt, this is the error I am getting. Just the first line without the additional warning messages though.

**Comment by MKLau** [comment]
Great, thanks Elizabeth!

**Comment by fong22e** [comment]
You are very welcome, Matt!

**Comment by tfjmp** [comment]
https://github.com/End-to-end-provenance/RDataTracker/blob/master/R/RDataTracker.R#L5433 << error should be there.

**Comment by tfjmp** [comment]
By any chance doing `library('CamFlowR')` before running your script fix the issue. In that case uninstalling CamFlowR library should fix it.

**Comment by MKLau** [comment]
Yeah, library(CamFlow) fixes this. 

This might be fixed by adding CamFlow to the DESCRIPTION and NAMESPACE files.

Seems like a hotfix.

**Comment by tfjmp** [comment]
If you don't install CamFlow, they should not be error. If you uninstall
it, you should be fine.

**Comment by fong22e** [comment]
Yes, that is true. Though this means (I hope that I am understanding this correctly) that if the user has CamFlow installed, to prevent the error, both DDGExplorer and CamFlow will be used when the user uses the command `ddg.display()`. The user is not given a choice to decide which visualiser they wish to use. Is this what we want to happen?

**Comment by erboose** [comment]
I think we want to give the user a choice of visualizers. The current version of CamFlow seems to bog down when loading larger ddgs.

**Comment by blernermhc** [comment]
I think the plan was that we wanted alpha users to see both visualizations rather than biasing them towards one or the other.  However, based on our meeting in November, it seems that CamFlow is not ready yet for alpha users.

**Comment by blernermhc** [comment]
I have placed the call to CamFlowVisualizer inside a tryCatch so that the user does not get an error message if the package is installed but not loaded with the library function.  This is in commit 394a78d1d9e0efd458b961bd22a87745662e2fe9
