### ISSUE TITLE
Environment remain a disjoint node

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#218]
We talked about it, but I am not sure I ever filled an issue about this.

Beyond being a bit vague in place e.g. https://github.com/End-to-end-provenance/RDataTracker/issues/184

The environment is currently a disjoint node.

![screenshot from 2017-01-06 09-24-54](https://cloud.githubusercontent.com/assets/1970355/21720612/2276ba76-d3f2-11e6-9d8b-f45dd870793f.png)

Libraries should also probably be nodes connected to the environment, rather than attributes as currently:
![screenshot from 2017-01-06 09-28-03](https://cloud.githubusercontent.com/assets/1970355/21720690/88cfc48e-d3f2-11e6-88f7-4bdb342cd1b9.png)

**Comment by blernermhc** [comment]
@fong22e Elizabeth, has this been fixed?

**Comment by fong22e** [comment]
Uh... What we have now is that the environment and library nodes are in the entity node.

```
“entity”: {
    // data nodes, if any

    // environment
    “environment”: {
        // things that go into the environment node
    },

    // library nodes
    “l1”: {
        // name, version, collection type
    },

    “l2”: {
        // name, version, collection type 
    }
}
```

Aside from having all these under the entity node, there is no explicit link, or edge, between them. 

Does this work?

**Comment by blernermhc** [comment]
This is done.
