### ISSUE TITLE
Delay in loading DDG Explorer under Windows

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#224]
When DDG Explorer is first loaded from RDataTracker (e.g. with the ddg.display command) there is a 1+ minute delay under Windows as RDataTracker tries to connect to a running server.  This problem is fixed by adding the argument "timeout=1" to the socketConnection call in ddg.display.

**Comment by blernermhc** [comment]
Are you planning to commit this change?

**Comment by erboose** [comment]
If you have time this week please go ahead and commit to master & development before the RStudio conference.  Maybe also address issue #223 as this will prevent use of the JSON file in some cases.

**Comment by blernermhc** [comment]
The timeout is set in commit 12f6864dc7093f954f8f43c88aefa31b924a34ee

**Comment by blernermhc** [comment]
Did you mean issue 222 as the other one you would like to see fixed?
