### ISSUE TITLE
Help file error

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#234]
I just tried to look at the help page in RStudio for ddg.run and got this error:  Error in fetch(key) : lazy-load database '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/RDataTracker/help/RDataTracker.rdb' is corrupt

**Comment by tfjmp** [comment]
That has been around for ages (as far as I remember). I assumed that I did not install something properly on my machine not knowing much about R.

**Comment by blernermhc** [comment]
I am pretty certain this worked at one point.  Maybe take a close look at messages from cran check?

**Comment by erboose** [comment]
Just downloaded and installed from master.  No problem with the RStudio help pages under Windows 7.

**Comment by MKLau** [comment]
Also no problem on my machine!

MacBook Air (13-inch, Late 2010)
OSX El Capitan 16.11.6

R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

RStudio
Version 0.99.896 – © 2009-2016 RStudio, Inc.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.2.14 (KHTML, like Gecko)

**Comment by MKLau** [comment]
Here's a post from someone else's repository (dated 2014). Based on it, it would be an issue with the R-Base package. 

https://github.com/hadley/devtools/issues/419

It also suggests to update your devtools package.

**Comment by blernermhc** [comment]
I have a suspicion that the problem arises when I update the RDT I am using by sourcing the package rather than going through the process of creating a package, installing it and loading it, which is cumbersome to do during development.

So, not something we should be concerned about.
