### ISSUE TITLE
Does RDataTracker record the version a dependent package was built under?

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#238]
I got this warning, but I don't see this information in the DDG Attribute List.

Warning message:                                                                                                                                             
 package ‘bipartite’ was built under R version 3.3.2

**Comment by blernermhc** [comment]
Is the bipartite package listed in the attributes?

Also, is there an error node that holds the warning message?

**Comment by MKLau** [comment]
Ah, yes to both! The package and its version are listed in the Attributes List. There is an error message in the DDG that captures that warning.
