### ISSUE TITLE
Collect provenance for functions in R packages

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#239]
At present we can collect provenance for statements inside user-defined functions.  But it would also be useful to have an option to collect provenance for statements inside functions located in R packages and called by the R script.  Here’s a possible strategy:

1. Get the source code for the function definition using the getAnywhere function (or the ::: operator).  The result may need to be massaged to remove ancillary information and achieve the proper format.

2. Create an assignment statement for the function definition.

3. Parse the assignment statement.

4. Insert the resulting expression into the set of expressions from ddg.source that will be processed by .ddg.create.DDGStatements.

If this approach were successful, the function definition would be annotated in the usual way and provenance would be collected for statements internal to the function.

**Comment by erboose** [comment]
This approach (if successful) could also be used to track what is happening inside base-R functions.  Consider the following two examples:

# Example 1
a <- c(1, 2, 3)
b <- 4
d <- append(a, b)

When the first example is executed with ddg.run, the final statement is captured in a single operational node in the ddg.

# Example 2
append <- function (x, values, after = length(x)) {
   lengx <- length(x)
   if (!after) 
      c(values, x)
   else if (after >= lengx) 
      c(x, values)
   else c(x[1L:after], values, x[(after + 1L):lengx])
}
a <- c(1, 2, 3)
b <- 4
d <- append(a, b)

In the second example the source code for the append function has been inserted into the script.  When this example is executed with ddg.run, the details of what the append function is doing are captured in the ddg.

**Comment by blernermhc** [comment]
I think it will be more complicated than that.  If the function that is included calls functions that are not exported from the package, then the annotated function would not work unless we also redefined the non-exported functions, since the new function would not have access to the non-exported functions.

I also note that getAnywhere says that it returns a list of matching objects, so we might not always get just a single answer.

I think it might be a better idea to leverage the library function.  We can see what libraries are loaded, find their source code, annotate the entire package, and then load the annotated library instead of the original.

**Comment by erboose** [comment]
Right, we would need to import non-exported functions called by the annotated function.  That could be done (in theory at least) by generating a list of such functions from the annotated function source code and the package namespace and using the package:::function operator.

Annotating the entire package would be simpler if there is some way to get the source code for an entire package.

In either case we might want some way to limit the amount of provenance collected, e.g. by asking the user to supply a list of package functions to annotate or by allowing the user to turn this feature on and off at particular points in the script.

**Comment by MKLau** [comment]
A couple of potentially (more or less) useful things:

ls('package:magrittr') will list the functions in a package. These only seem to be those that are exported; however, I think that the pos argument should provide access to the rest of the functions. 

.libPaths() gives the local path of installed packages. I dug into them a little bit though and the files are not organized the same way as the source code from tarballs. I can't actually locate the source code.

**Comment by erboose** [comment]
ls(getNamespace("magrittr"), all.names=TRUE) returns a complete list of package functions (exported and non-exported).

**Comment by MKLau** [comment]
Nice!

**Comment by erboose** [comment]
Here’s one way to get the source code for library functions:

1. Use sessionInfo()$otherPkgs to get a list of loaded packages.
2. Use ls(getNamespace(package.name)) to get a list of functions for each package.
3. Use package.name:::function.name to get the source code for each function.

I created an R script to do this and tried it on Matt’s script (model_nestedness.R). This script loads 2 libraries which in turn load 9 other libraries.  The resulting source code for all 11 libraries is about 60,000 lines!

So we may want to consider options for limiting the amount of source code to be annotated.  One approach would be to have the user identify library functions of interest.   Another would be to scan the user’s script and identify any library functions that are called .  Either way we’d need to track down any unexported functions that are called by these library functions (directly or indirectly) and collect the source code for those unexported functions as well.

**Comment by blernermhc** [comment]
This seems to not be one of our goals any longer.  It would be too fine-grained and would require modifying a library function to add the annotations.
