### ISSUE TITLE
Error in lvalue[[2]]: subscript out of bounds\n

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#248]
Caroline Juang and I encountered this error yesterday when we were working on her thesis script. She ran it on her machine (Windows) and then I ran it on my machine (details below) with both the development and master branches and both produce this error. 

I tracked it down to one particular part of her code, which I've isolated in the details below. It seems to have something to do with the assign function, so I'm tagging Elizabeth onto this. As a lead, I did some though and found that it might be linked to .ddg.get.var. 

Here are the details from my machine: 

### Environment
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch       

### RDataTracker Input

hffill <- matrix(100,10)
year <- 2010
assign(paste("Resids", year-2, year+2, sep="."),rep(NA, nrow(hffill)))

### RDataTracker Output

[1] "Error in lvalue[[2]]: subscript out of bounds\n"
[1] "Saving ddg.txt in /Users/hermes/Desktop/example_debug_ddg"
[1] "Saving ddg.json in /Users/hermes/Desktop/example_debug_ddg"

### RDataTracker Results

Architecture="x86_64"
OperatingSystem="unix"
Language="R"
LanguageVersion="R version 3.3.2 (2016-10-31)"
RDataTrackerVersion="2.25.0"
Script="/Users/hermes/Desktop/example_debug.R"
SourcedScripts=""
ProcessFileTimestamp="2017-02-11T14.56.24EST"
WorkingDirectory="/Users/hermes/Desktop"
DDGDirectory="/Users/hermes/Desktop/example_debug_ddg"
DateTime="2017-02-11T15.28.29EST"
InstalledPackages="RDataTracker 2.25.0"
1
Operation p1 "1-tryCatch" Value="tryCatch" Time="4.307" Script="NA" Pos="NA";
Exception d1 "1-error.msg" Value="\"Error in lvalue[[2]]: subscript out of bounds \"";
DF p1 d1

**Comment by fong22e** [comment]
Unfortunately, using the `assign(...)` function will throw the error. This is related to issue #153 .

**Comment by MKLau** [comment]
Oh, I completely forgot about #153.
