### ISSUE TITLE
Don't modify user environment

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#260]
I did not follow the latest of RDataTracker, but we must make sure it does not modify the user environment.

Recordr has been removed from CRAN for policy violation, for this very reason.

Details here: https://github.com/NCEAS/recordr/issues/64

**Comment by blernermhc** [comment]
By default, provenance is stored in R's temporary directory.  The user needs to explicitly name a directory to do otherwise so we believe this would address CRAN's concern.
