### ISSUE TITLE
Data frame with factor

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#267]
We were testing the valType with caroline and it does not seem that `data frame with vector` seems never used. However, we saw data frame(numeric, factor) in our example.

https://github.com/End-to-end-provenance/RDataTracker/blob/master/R/RDataTracker.R#L1392

On a side note: can we get type that do not contain spaces (i.e. data_frame rather than data frame)

**Comment by fong22e** [comment]
Hi Thomas! What is the example you are using?

**Comment by tfjmp** [comment]
Not sure, @MKLau may know?

**Comment by fong22e** [comment]
Hi Thomas! I assume you meant `data frame with factor`, not `data frame with vector`?

Currently, `data frame with factor(numeric, factor)` is a possible outcome. Does that seem redundant? Should we just say `dataFrame(numeric,factor)` for cases with factors, or `data_frame(numeric,factor)`?

**Comment by tfjmp** [comment]
Yes with factor sorry.

dataFrame or data_frame, does not really matter as long as there is no spaces.

I was also thinking that we could actually be json compliant.

i.e. something along the line:
```
valtype={container="data frame", type=["numeric", "factor"]}
valtype={container="vector", type=["numeric"]}
valtype={container="list", type=["numeric"]}

I am in a meeting, so cannot check json synthax, but following it would greatly help with the parsing.

**Comment by tfjmp** [comment]
@cjuang may also have insight on the matter.

**Comment by tfjmp** [comment]
Also inline with the other issue #268, maybe also reporting the size when/if available.

**Comment by MKLau** [comment]
Oh, this is from the eep-usecases. Caroline knows the exact one, but I think that is coerce.R

**Comment by cjuang** [comment]
@MKLau  Yes, the one I was testing was coerce.R from eep-usecases.

One of the valtypes I saw in the ddg.json file was `data frame (integer,factor)` so we were unsure what cases used `data frame with factor`. Something without spaces or similar to what @tfjmp suggested may help.

**Comment by MKLau** [comment]
@fong22e

Caroline's comment made me wonder, is there a reason to have "data frame" and "data frame with factor"? 

Is this just an artifact from the initial val type implementation?

**Comment by blernermhc** [comment]
Right, I think that is a leftover from when we started with a more narrow focus on factors.  Now that we are recording the type of each column, factor shows up as a column type and it seems sufficient to just say "data frame".

**Comment by MKLau** [comment]
Great, that should simplify the val_type capture function.

**Comment by fong22e** [comment]
[ValType.pdf](https://github.com/End-to-end-provenance/RDataTracker/files/988199/ValType.pdf)

Here is a document about the current implementation and questions regarding enhancing the annotation of ValType. Please let me know what would be the best options going forward. Thank you!!!

**Comment by MKLau** [comment]
Awesome, thanks Elizabeth! I'll take a look tomorrow
