### ISSUE TITLE
Namespace issue 

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#275]
From a recent build of master:

Consider adding
  importFrom("grDevices", "dev.copy", "dev.copy2pdf", "dev.cur",
             "dev.list", "dev.off", "dev.print", "dev.set", "pdf")
  importFrom("methods", "new")
  importFrom("utils", "capture.output", "getParseData", "head",
             "installed.packages", "object.size", "packageVersion",
             "savehistory", "tail", "timestamp", "write.csv")
to your NAMESPACE file (and ensure that your DESCRIPTION Imports

**Comment by MKLau** [comment]
@blernermhc

**Comment by blernermhc** [comment]
# CRAN check gives errors if these are not included.
# However, if we include these, ddg.run crashes R when run 
This is a known problem.  If you look in the NAMESPACE file, you will see this comment.  We have tried adding these import statements at least twice and it leads to a bizarre bug on Windows.  After spending too much time tracking it down, I added this comment to our NAMESPACE file the last time:

# CRAN check gives errors if these are not included.
# However, if we include these, ddg.run crashes R when run 
# in RStudio on Windows.  It does not crash on Mac.  It 
# also does not crash on Windows using the standard R environment.
#importFrom("grDevices", "dev.copy", "dev.copy2pdf", "dev.cur",
#           "dev.list", "dev.off", "dev.print", "dev.set", "pdf")
#importFrom("methods", "new")
#importFrom("utils", "capture.output", "getParseData", "head",
#           "object.size", "packageVersion", "savehistory", "tail",
#           "timestamp", "write.csv")

**Comment by MKLau** [comment]
Sorry Barb for re-hashing this. I'll close this again.
