### ISSUE TITLE
DIR_LOCAL failing automated test

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#276]
I simplified depends.r for the time being see https://github.com/tfjmp/RDataTracker/commit/9f10ae81d058204298cc24c2b257b4c4ee2e2228

However, Travis does not seem to particularly like the following:
```
## Directories
testDir <- "[DIR_LOCAL]/"
setwd(testDir)
```

The error is the following:
```
Error in setwd(testDir) : cannot change working directory
```

**Comment by MKLau** [comment]
Yeah, my guess would be that the directory path is not correctly defined. But, I'm not familiar enough with that script.

**Comment by blernermhc** [comment]
What script are you looking at?  Is this tests/sourceTest.r?  That is a generic test script.  When we run our regression tests, our ant test script copies this generic test script into the directory of the script we are testing and replaces DIR_LOCAL with the actual directory the test is running in.  So, by the time the setwd call is made there is an actual directory name there.  Maybe you can just tell Travis to ignore tests/sourceTest.r?

**Comment by tfjmp** [comment]
Yes `tests/sourceTest.r` is the file concerned.

Sadly it has little to do with Travis which is merely trying to run CRAN check at this stage. It is `R CMD check --as-cran xxx` that is failing. Ideally the test should be CRAN friendly (or at least not break their checking tool).

The complete log is available here: https://travis-ci.org/tfjmp/RDataTracker/builds/234090046

**Comment by blernermhc** [comment]
Since it is never actually run as is, we could check the suffix to be something other than .r.  Probably the ant file needs to change, then, so that it when it copies sourceTest.r, it reintroduces the r suffix.  Anyway, would changing the .r to .rtest or .rtemplate make the CRAN check happy?

Is the plan to include all of these tests in the R package?  That may be overkill.

**Comment by MKLau** [comment]
Hi Barb, yeah, I think changing the suffix to rtest might make it so that the R check ignores that file. I didn't realize that the R CMD check would run the scripts in the tests folder. That's really interesting. Given that many of these tests are not easy to automate, perhaps a more parsimonious solution would be to move the test scripts into a separate repo.

**Comment by blernermhc** [comment]
The ant file only runs R CMD check on the actual R files that make up RDataTracker, not the test files since they are not included in the R package.  I don't know whether you can do something similar with Travis.  

I worry about putting the regression tests in a separate repo since the expected results change as RDataTracker gets modified, so the regression test results are tightly bound to specific versions of RDataTracker.

**Comment by MKLau** [comment]
I see what you mean. Having the tests for the package is imperative. I'm not sure what the best answer to this is, but your suggestion of having travis ignore the tests would bf simpler if it's possible.

**Comment by tfjmp** [comment]
They are included in the R package. You need to create a Rbuildignore file and populate it properly (which I have now done on my branch). We are distributing our package through github, people installing through github are not, never, ever using the ant files. That means things need to be done following R standards. Ideally if possible we should switch away from ant all together and use something like `testthat` https://github.com/hadley/testthat

I am not sure if that's possible, but that is what most package seems to be using, and what most of documentation I found say we should be using. Is it even possible to use it?

On a side note what is using `utilities`?

There is stuff in there with absolute path that make no sense outside of a very well defined machine:
`/Users/blerner/Documents/Process/DataProvenance/github/RDataTracker`
`D:/Users/Luis/Documents/Harvard School Work/Summer 2014/RDataTracker`

That needs to be looked at and cleaned (or removed if nothing is using it).

**Comment by blernermhc** [comment]
Can you say where these paths are occurring?  If they are in the testing scripts, that is what we expect to happen as the testing scripts are generated automatically by ant.

I would not expect that anyone using install_github or installing as an R package would use our existing tests and ant files.  They are there for people doing development, so us and anyone who clones our repository.  

What are the R standards for including tests inside R packages?  Where can we find documentation on that?

**Comment by tfjmp** [comment]
There is Hadley Wickham "blog post" on the matter:
http://r-pkgs.had.co.nz/tests.html

There is a note about CRAN and test at the bottom of his post.

The absolute paths are in `utilities/interactiveTimer.r` and `utilities/scriptTimer.r`, `utilities/timerFunctions.r` and `utilities/plot.r`. Note that there may be more files containing absolute paths, but those are the files I know of.

If what is in `utilities` is generated automatically, it may be best to delete the files from the repository and add them to the `.gitignore` list.

**Comment by blernermhc** [comment]
The utilities folder contains scripts that Luis created a couple of years ago but that we are no longer using.  It would be ok with me if these were moved out of RDataTracker and maybe saved in dev or someplace.  I would prefer not losing track of these completely.

**Comment by tfjmp** [comment]
If they are "deleted" from the current dev/master they will remain in the version control if we ever need them back. Is that ok (I would assume so)?

**Comment by blernermhc** [comment]
We'd have to remember they existed, though, right?  That seems unlikely if they are not visible at all.

**Comment by MKLau** [comment]
As long as we don’t “delete" them from the version tree they would be searchable.

I agree with Barb’s suggestion that we should keep them in dev or another repo. Also, we should definitely grab another tarball of master and put that in the dropbox folder.


On May 24, 2017, at 4:08 PM, blernermhc <notifications@github.com<mailto:notifications@github.com>> wrote:


We'd have to remember they existed, though, right? That seems unlikely if they are not visible at all.
