### ISSUE TITLE
Identifying data being plotted

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#283]
The DDG does not make it easy to determine what data is involved in creating a plot.  In particular, if you try to follow a data path back from a file containing a plot, you will only see that it was produced by dev.off, which has no input parameters, so the data path ends there.

It would be better if we saw as input the data that was being plotted.  That would require doing something special with plots and recognizing the function call that puts the data into the plot.  Perhaps there are a limited number of such calls so that doing that specialization would make sense.  It would certainly be useful.

**Comment by tfjmp** [comment]
Is this the same issue as reported there last year:
https://github.com/End-to-end-provenance/RDataTracker/issues/137

**Comment by blernermhc** [comment]
It is the same as the part of that issue that is about the jpeg output and dev.off.

**Comment by tfjmp** [comment]
Duplicated issue. Closing.

**Comment by blernermhc** [comment]
I'd like to keep this issue open.  #137 seems to have several issues bundled together and I find it easier if an issue focuses on a single problem.

**Comment by blernermhc** [comment]
The graphics branch has a 1st version of code to support this.  Feel free to give it a try and let me know if this is what you want.  

Caveats:
- Only works for the base graphics package
- Only works if a call is made to open a device to plot to, like pdf, jpg, X11, etc.
- Only works if the device is closed with a call to dev.off()

Here is a sample script that it works well on.

[graphics2.R.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1110145/graphics2.R.txt)

**Comment by blernermhc** [comment]
@tfjmp Let me know if this is what you'd like to see.

**Comment by tfjmp** [comment]
@blernermhc just run a few example, but it looks to be working!

**Comment by blernermhc** [comment]
This works when the base graphics package is used.  It could be extended to support other packages, like ggplot2.
