### ISSUE TITLE
ddg.json is not a valid son object.

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/RDataTracker#284]
I discovered this when I was writing a small script to convert ddg.json to a python object. I got an error when I ran my program, so I tested my ddg.json in an online json parser, which indicated that the json contained a syntax error. Specifically, in the line `"rdt:sourcedScripts": ,`.
I added an empty string following the colon so that it looked like the rest of the json, and the file parsed as valid.
My guess is that this is really simple in that if there are no sourced scripts, RDataTracker doesn't add anything to ddg.json instead of adding an empty string like everywhere else.
[ddgjson.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1045535/ddgjson.txt)
[Example_0R.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1045539/Example_0R.txt)

**Comment by fong22e** [comment]
Hi @NullCGT ! I just ran your example file using ddg.run, using the code from the development branch. This is the line in the generated `.json` file.
```
"rdt:sourcedScripts" : ""
```
Was this what you were looking for?
[ddg.json.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1050084/ddg.json.txt)

**Comment by NullCGT** [comment]
That’s what should be generated, but for some reason mine generated “rdt:sourcedScripts” : with no empty string after it, resulting in an invalid json object.


On Jun 3, 2017, at 10:57 PM, Elizabeth Fong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @NullCGT<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nullcgt&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=71R_cCI167xkBonU5aVMe8APIucaLp3jqKkgvSeZtWg&m=HIP8IUyyUuaEBxo0FxdtS5FH4j65eGq_Ew9Ucd1yu_k&s=s878aSe58NWBQ9bsH2HH4Wg6PMJB1e5KxOS8ka148zg&e=> ! I just ran your example file using ddg.run, using the code from the development branch. This is the line in the generated .json file.

"rdt:sourcedScripts" : ""


Was this what you were looking for?
ddg.json.txt<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_End-2Dto-2Dend-2Dprovenance_RDataTracker_files_1050084_ddg.json.txt&d=DwMFaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=71R_cCI167xkBonU5aVMe8APIucaLp3jqKkgvSeZtWg&m=HIP8IUyyUuaEBxo0FxdtS5FH4j65eGq_Ew9Ucd1yu_k&s=TBDfkmUZKFBmIyD9ZEqFWW3AJ1JWgqxARd7tZN-tDDw&e=>

**Comment by fong22e** [comment]
Which branch of the code are you running? As in, is the installed RDataTracker taken from the `development` branch, `master` branch, or another branch?

**Comment by NullCGT** [comment]
I believe that was in master, but I’ve been working more recently in development so I can see if I can recreate it there.
On Jun 3, 2017, at 11:25 PM, Elizabeth Fong <notifications@github.com<mailto:notifications@github.com>> wrote:


Which branch of the code are you running? As in, is the installed RDataTracker taken from the development branch, master branch, or another branch?

**Comment by fong22e** [comment]
Oh this is odd... I just installed RDataTracker from the master branch and ran the code. The empty string is present after the `"rdt:sourcedScripts"` section.
[ddg.json.txt](https://github.com/End-to-end-provenance/RDataTracker/files/1050097/ddg.json.txt)

**Comment by fong22e** [comment]
Hey @NullCGT ! How's this going? Is there anything that I can help with?

**Comment by NullCGT** [comment]
Sorry, I’ve been working on the hashtable stuff! I can take a look at it tomorrow, I know where the code is that writes out json, so it should be relatively quick.
On Jun 6, 2017, at 5:23 PM, Elizabeth Fong <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @NullCGT<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_nullcgt&d=DwMCaQ&c=HUrdOLg_tCr0UMeDjWLBOM9lLDRpsndbROGxEKQRFzk&r=71R_cCI167xkBonU5aVMe8APIucaLp3jqKkgvSeZtWg&m=GjWjinLT3GhB09EyXfBeT8pOVf8N7XEPyaIQoDXC5y8&s=sHgNOvPntmt0HGIa6cWDkKzNZuHwwKDlY5KVkYBawbk&e=> ! How's this going? Is there anything that I can help with?

**Comment by fong22e** [comment]
Thank you so much! Please let me know if there's anything I can help with!

**Comment by NullCGT** [comment]
I’m in my branch off of development, and I can’t seem to duplicate it. I took a look at the code that generates the json and everything seems all right.

Connor

On Jun 6, 2017, at 5:26 PM, Elizabeth Fong <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you so much! Please let me know if there's anything I can help with!

**Comment by MKLau** [comment]
Great, I'm closing this. Thanks folks!
