### ISSUE TITLE
File writing functions

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#289]
Determine what other file-writing functions we should look for.  In particular, writeLines is missing.

**Comment by NullCGT** [comment]
I've been building up a list of these, since they relate pretty closely to the work I'm doing with hashtables and file read/writes. Should I add them to the list in the hashtable2 branch?

**Comment by blernermhc** [comment]
With the connection code, I added a lot more functions.  We might want to look into using the trace function to deal with reading and writing files and figure out if that allows us to monitor fewer functions.  For example, there may be some basic "write" function that they all end up calling.

**Comment by blernermhc** [comment]
I/O tracing code now traces more functions.
