### ISSUE TITLE
Texlive update failing travis

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#294]
Known (recent) issue, see here: https://github.com/travis-ci/travis-ci/issues/7852 and here: https://github.com/craigcitro/r-travis/issues/174

```
tlmgr update --self
TeX Live 2016 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.
If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /home/travis/texlive/tlpkg/backups
TLUtils::check_file: removing /tmp/dcZbCPC9G1/14nlUCRRZL/texlive.infra.tar.xz, sizes differ:
TLUtils::check_file:   TL=200472, arg=194264
TLPDB::_install_package: downloading did not succeed
tlmgr: Installation of new version of texlive.infra failed, trying to unwind.
[1/1, ??:??/??:??] update: texlive.infra [190k] (41280 -> 41476) ... tlmgr: Restoring old package state succeeded.
done
tlmgr: action update returned an error; continuing.
tlmgr: package log updated: /home/travis/texlive/texmf-var/web2c/tlmgr.log
tlmgr: An error has occurred. See above messages. Exiting.
The command "tlmgr update --self" failed and exited with 1 during .
```

**Comment by MKLau** [comment]
@tfjmp So, does Travis need to update it's TexLive version on the sever?

**Comment by MKLau** [comment]
Also, I've never used the BLOCKED label for an issue. What does it generally mean?

**Comment by tfjmp** [comment]
@MKLau: Yep apparently it happens every year. Looking at the issues this morning the patch is done, they are waiting for deployment, so it should be working as normal in a bit.

@MKLau: From my day in software engineering `blocked` generally means you cannot complete the task, because you are dependent on another task that is not done (or waiting for customer feedback etc... generally something you can do nothing about). In that case I cannot solve the issue until the travis people deploy the patch (and it seems I will have nothing to do at all ^^).

**Comment by MKLau** [comment]
Great, that makes sense, thanks!

**Comment by tfjmp** [comment]
Seems to be working now. Closing!
