### ISSUE TITLE
Add data flow edges for identical files

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#300]
The met-real-time.R script reads in a data logger file, saves the 15-minute data as a new file (m101.csv), and then reads this file into a dataframe.  In the current DDG, there are two input data nodes for m101.csv but they are not connected.  This might be an opportunity to use the file name, path, and hash value to verify that the files are identical and add the corresponding data flow edge (just as we use scope to verify that two variables with the same name are identical).

**Comment by MKLau** [comment]
@erboose Is this an issue with RDataTracker or with DDG-Explorer? I.e., is there an issue with the details recorded in the ddg.json?

**Comment by erboose** [comment]
It would be an enhancement for RDataTracker.

**Comment by blernermhc** [comment]
Redundant with issue #457
