### ISSUE TITLE
Generate new feature CHANGELOG 

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#306]
Hey @fong22e, see the changelog in the repo to see the structure. I've been generating the by parsing the git log to only show the major changes. For the most part, these are now pull requests from feature branches. So, seems like there should be a way to automate this. One thing that won't be automatable, is the Known Bugs. You can find these easily though by going to the issue list and sorting by the bug label.

**Comment by blernermhc** [comment]
According to Hadley WIckham, NEWS.md is more useful to highlight changes users care about.  See the NEWS.md section of http://r-pkgs.had.co.nz/release.html

**Comment by blernermhc** [comment]
We now have NEWS files.
