### ISSUE TITLE
Error in block[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#313]
I'm looking to collect provenance for the network analysis I'm running for the Germany meeting, and I'm getting this error on both master and development branches.

I get it when running the following from my main project directory for (https://github.com/HFpostdoc/multilayer-foodwebs.git)

ddg.run('src/pp_nets.R')

Perhaps it has something to do with sourcing from outside of the script's directory (i.e. src/pp_nets.R as opposed to pp_nets.R).

**Comment by fong22e** [comment]
Hi Matt, the link is giving me an error 404...

**Comment by MKLau** [comment]
Try this https://github.com/HFpostdoc/multilayer-foodwebs

**Comment by erboose** [comment]
Does the error occur if provenance collection inside functions and control constructs is turned off?  I.e. annotate.inside = FALSE in ddg.run or ddg.set.detail(0) at the R command line.

**Comment by erboose** [comment]
The default is to collect provenance inside functions and control constructs for one loop iteration (level 1).

**Comment by MKLau** [comment]
Ok, that is the setting that produced the error. I can try reducing to the lesser setting after lunch.

**Comment by MKLau** [comment]
Ran with detail set to 0 and the error no longer occurs.
