### ISSUE TITLE
Simplify RMarkdown Test script

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/RDataTracker#314]
The RMarkdown test contains an extremely large number of libraries used in the RMarkdown test file, which may be causing Travis to indicate failures when it should not.
This script is located at RDataTracker/Tests/RMarkdownTest/RMarkdownTest.Rmd.

**Comment by MKLau** [comment]
There is now a reduced RMarkdown script on the *reducermd* branch.

**Comment by MKLau** [comment]
@NullCGT I'm going to close this, but feel free to re-open if you'd like me to change the Rmd file.
