### ISSUE TITLE
Console mode capture is limited by R's history cap of 512 lines

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#316]

**Comment by MKLau** [comment]
Check if newer version of R allows user to change history line limit.

Make sure to test on all OS platforms.

**Comment by blernermhc** [comment]
Resolved.  We no longer use the history file to implement console mode.  Changed in https://github.com/End-to-end-provenance/RDataTracker/commit/3a1b16cd3e31c5056ed9bef9e821775ebe9ca487
