### ISSUE TITLE
Having a look at terminology

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#323]
I know everyone is very attached to the term "DDG", but for the sake of working as part of the community and making it easy for users. Could we think about using "provenance" or "provenance graph"?

**Comment by blernermhc** [comment]
I tend to say provenance graph when talking to people outside our group.

**Comment by tfjmp** [comment]
I meant in the documentation, issues, code etc... not when you talk to someone.

**Comment by MKLau** [comment]
Yeah, I'd be on board with that. DDG is specific to data, as in Data Derivation. I'd suggest that when people see some docs with DDG, log an issue and we can update where appropriate to Provenance Graph.

**Comment by tfjmp** [comment]
Also as discussed this morning, checking if it would be ok to switch from `ddg.xxx` to `prov.xxx`. Need to check than no other package use this, if not co-opt the name.

**Comment by MKLau** [comment]
I found this on Stackoverflow (https://stackoverflow.com/questions/11379807/list-all-functions-on-cran). 

library(sos)
findFn("adply")

I'll see if it will search with wildcards too.

**Comment by tfjmp** [comment]
Sounds neat.

**Comment by MKLau** [comment]
"","Function","Package"
"1","incomedata","sae"
"2","pssynt","sae"
"3","sizeprov","sae"
"4","sizeprovage","sae"
"5","sizeprovedu","sae"
"6","sizeprovlab","sae"
"7","sizeprovnat","sae"
"8","direct","sae"
"9","ebBHF","sae"
"10","pbmseebBHF","sae"
"11","ssd","sae"
"12","DataPackage-class","datapack"
"13","describeWorkflow","datapack"
"14","insertRelationship","datapack"
"15","recordDerivation","datapack"
"16","createFromTriples","datapack"
"17","getRelationships","datapack"
"18","ResourceMap-class","datapack"
"19","serializeRDF","datapack"
"20","Query-class","redland"
"21","QueryResults-class","redland"
"22","freeQuery","redland"
"23","freeQueryResults","redland"
"24","screen.frames","FlowScreen"
"25","station.info","FlowScreen"
"26","screen.series","FlowScreen"
"27","screen.summary","FlowScreen"
"28","nextItem","catR"
"29","startItems","catR"
"30","EMMA","sommer"
"31","MEMMA","sommer"
"32","epi.cluster2size","epiR"
"33","mscstn","seas"
"34","models","caret"
"35","BASE.URL","CHCN"
"36","occ2df","spocc"

**Comment by tfjmp** [comment]
Does it means it would be safe to migrate to prov.xxx from ddg.xxx ?

**Comment by MKLau** [comment]
Looks like it to me. I don't see anything that uses "prov.*"

**Comment by MKLau** [comment]
Since we've initiated the pull request #367, I'm closing this discussion.
