### ISSUE TITLE
Make Travis fail for CRAN check error

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#329]

**Comment by tfjmp** [comment]
To be sure I understand, do we want it back to the original setting?

**Comment by blernermhc** [comment]
I don't know what the original setting is.  What we want is for it to fail if the check task reports an error.  Not the Cran check task.  Also, we want to allow it to succeed if check produces warnings or notes; only fail on errors.

**Comment by fong22e** [comment]
Is this for CRAN errors or for regression test errors?

**Comment by MKLau** [comment]
Hi Elizabeth, it doesn't look like we fully resolved this issue, but I recall that this was testing with CRAN's checks, i.e. 'R CMD check --as-cran'.

**Comment by tfjmp** [comment]
My recollection of events is that originally the RDataTracker library was tested for CRAN compatibility (it was not). We then decided it was not of importance and that the test needed to pass as we will not be fixing the problem (and it may not have been possible to do so). Later on it emerged that we actually wanted to test for CRAN compatibility. 

My current understanding is that Matt is hard working on some alternative library (ProvR or his work with Elizabeth) that will be designed to go on CRAN even if it implies less features. My best interpretation of the situation is that you can close this safely for now.

**Comment by MKLau** [comment]
I would agree with Thomas' perspective on closing this issue. Relating to RDT, checking for CRAN compatibility is likely not going to pass. 

I think an open question, prior to closing, would be whether or not to have an R CMD check --as-cran or just vanilla checks.

I would recommend going over the info that the checks supply and seeing what's relevant to development.
