### ISSUE TITLE
Ant test script on Windows Computers

### ISSUE THREAD

**Issue by kandluis** [End-to-end-provenance/RDataTracker#33]
The ant test script depends on the diff command which is NOT available on Windows by default:
http://stackoverflow.com/questions/6877238/what-is-the-windows-equivalent-of-the-diff-command

If developing on Windows, Cywin will need to be installed. There does not seem to be a comparable utility for Windows.

**Comment by blernermhc** [comment]
Continues to be an issue, but referenced elsewhere.
