### ISSUE TITLE
How to relate statement to package?

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/RDataTracker#331]
When parsing the graph we would like to know if the function(s) in a statement are part of a particular package. What is the right way to integrate this into the provenance?

**Comment by blernermhc** [comment]
Currently, we do not capture information about functions that come from packages, only functions that are defined in the same script or a sourced script.  Emery is working on something to collect provenance from within library functions.

It sounds like you are interested in something in between.  Can you say more about what you would like to know?

For example, if a line of code contains:
a (b (c (d)))

You would want to know where a, b, and c were defined.  Is that right?  Currently, that statement would all be captured with one node, so we would need to attach a list of information about those functions to that one node.

Also, if a call happens inside an if-statement, we do not always know which branch of the if was taken:

if (a) b
else c

What would you want the provenance to include if we didn't know which branch was taken?  This can also happen with loops or with functions called from within functions.

**Comment by tfjmp** [comment]
> You would want to know where a, b, and c were defined. Is that right? Currently, that statement would all be captured with one node, so we would need to attach a list of information about those functions to that one node.

Correct. The idea is taking a list of statement in the provenance graph, I should be able to list the dependencies required to run those statement. In our scenario, the code or provenance within those function is not necessary nor relevant.

> Also, if a call happens inside an if-statement, we do not always know which branch of the if was taken:

> if (a) b
> else c

> What would you want the provenance to include if we didn't know which branch was taken? This can also happen with loops or with functions called from within functions.

If it cannot be known, taking a conservative approach would be preferable. It is in my view better to include more dependencies than necessary rather than not enough.

At the moment in our prototype we are being extremely conservative and including all listed dependencies, we probably would want to do better than that in the future.

**Comment by MKLau** [comment]
Thanks to the NAMESPACE of each package, the functions from package dependencies should each have it's namespace information attached to it at the time that it is executed. This is the kind of information that I think I would want collected. 

I'm not sure how to get that information though. 

Also, seems like user defined functions could be an issue, as they don't have a NAMESPACE, but I suppose they would have a prov lineage that would be traceable back to some definition of a function or *source* call.

**Comment by MKLau** [comment]
Relates to issue #239

**Comment by blernermhc** [comment]
Is your goal to know which packages are being used, or do you want to know specifically which functions are being used in each package?  The answer to do that could affect how we approach this.  For example, in the a(b(c(d))) case, would it be enough to have a packages-used attribute that said "package1, package2", or would you want to know that function a came from package1 and function b came from package2?

**Comment by MKLau** [comment]
I think the latter example, a came from pkg1 and b from pkg2. More specifically, I want to be able to distinguish the case of pkg1 and pkg2 and potentially the user all define a function called "a". 

We potentially need to know this so that we can distinguish that a specific execution of a function was the function from pkg1, pkg2 or user. 

This happens fairly regularly. In fact, just this morning Caitlin was having issues with the "diff" function, which is defined in the base package. However, she had re-defined it in her script because she had mistyped the name of a function she had written. Then, all of a sudden her script was no longer running, even though it had just been running yesterday evening.

**Comment by tfjmp** [comment]
> Is your goal to know which packages are being used, or do you want to know specifically which functions are being used in each package? The answer to do that could affect how we approach this. For example, in the a(b(c(d))) case, would it be enough to have a packages-used attribute that said "package1, package2", or would you want to know that function a came from package1 and function b came from package2?

In our particular scenario we want to know which packages are used by a statement, it does not really matter which function comes from which package.

**Comment by blernermhc** [comment]
You gave opposite answers.  

For CodeCleaner purposes, I think you would just need packages / statement.  To support debugging the problem Matt reports, you need the more detailed solution.

Maybe you 2 can discuss and let me know what you decide?

**Comment by tfjmp** [comment]
I am not talking about debugging, but having more detailed information would work too. I can do less with more. So Matt proposal would work just as well.
