### ISSUE TITLE
File nodes when dev.off is present (PlotTest)

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#333]
When `dev.off()` is present in the script such as in the case of `PlotTest`, a file node is also added to the end of the script like in cases where `dev.off()` calls are not present.

![plottest_ddg](https://user-images.githubusercontent.com/20979904/27717049-98624514-5d10-11e7-8102-9b48bdc4114b.png)

**Comment by blernermhc** [comment]
Fixed with graphics tracing code.
