### ISSUE TITLE
SHA-1 Hashes may differ on 32 and 64 bit systems.

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/RDataTracker#345]
When doing file hashing, the sha-1 hash may not be consistent across different file systems. This is because I used the digest function instead of the sha1 function, since the sha1 function does not seem to be able to read in files, only R objects. If someone who knows R better than I do could let me know if there is a way to "load" a file as an R object, that would be great.

https://cran.r-project.org/web/packages/digest/digest.pdf

Note: This issue also stems from a larger one, which is that we don't know exactly what SHA-1 algorithm noworkflow uses for hashing, so we don't know if it will be one hundred percent consistent without testing, or whether it suffers from this issue as well.

**Comment by blernermhc** [comment]
The sha1 function in the digest package claims to produce the same hash on 32-bit and 64-bit.  There are some additional, optional parameters, though, and those could be set differently in different systems, so it is still not entirely clear how to handle this.

**Comment by blernermhc** [comment]
We now use md5 as the default.  Does that have the same issue?
