### ISSUE TITLE
RDataTracker filePipeline branch fails basicTest due to pdf output

### ISSUE THREAD

**Issue by NullCGT** [End-to-end-provenance/RDataTracker#346]
RDataTracker's filePipeline branch currently fails Travis tests because at least one test uses pdf output. PDFs use timestamps, and thus their SHA-1 hashes will differ. This shouldn't be too much of an issue in regular use, since reading in PDFs is not something normally done. One possible fix for this is modifying the travis test code to ignore pdf hashes.

**Comment by blernermhc** [comment]
Travis ignores hash values.
