### ISSUE TITLE
Resolve merge conflicts between master and development

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#352]
Hi Barb and Emery, I just took a look at the merge conflicts between master and development. It's going to require one of you to get this fixed. 

I suggest merging the changes that exist in master into development. 

Make sure that no one merges into development while the merge conflicts are being resolved. 

Once that's done, development should be tested and then we can merge development into master with our new features.

**Comment by blernermhc** [comment]
I'll look at this this afternoon.

**Comment by blernermhc** [comment]
This is done.
