### ISSUE TITLE
Priorities for 2.27.0

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#353]
Hi All, this is my take on priorities for getting master up to speed with development and having a more stable development branch as well:

1- PROV-JSON that is being produced is correct
2- Error Block (Issue #313) is fixed
3- Regression testing fails are correctly captured by Travis CI (Issue #337)
4- Graphics details are being captured to get provenance for base plotting
5- Hash output is in JSON
6- Works on all major platforms

Things that can wait to 2.28.0:
a- Function dependency information
b- Calls to graphics device implementation of graphics capture
c- Collect internal provenance
d- Remove ddg.txt completely
e- Change language from ddg to prov

**Comment by tfjmp** [comment]
That looks like a solid plan.

**Comment by blernermhc** [comment]
The URL associated with issue 313 does not work.  Is that problem fixed?

**Comment by blernermhc** [comment]
I think issue 337 is fixed.

**Comment by MKLau** [comment]
Hi Barb, #313 is still open, the link works for me. Here's the full url: https://github.com/End-to-end-provenance/RDataTracker/issues/313

**Comment by blernermhc** [comment]
I can get to the issue.  I just can't get to the script referenced in the issue.

**Comment by tfjmp** [comment]
Concerning 1) we could use the following [tool](http://xmodulo.com/validate-json-command-line-linux.html) as part of the ant test script. However, it would require to define/extend the [PROV-JSON schema](https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/schema).

**Comment by blernermhc** [comment]
I think adding json validation to the test script would be great.

**Comment by MKLau** [comment]
I've added a new issue to address this.

**Comment by blernermhc** [comment]
The only remaining open issues are number 2 and item c.  Item c is covered in multiple other issues and will be addressed after the CRAN release.  The CRAN release will not include provenance internal to functions.
