### ISSUE TITLE
Hashtable written to both csv and json

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#356]
The hashtable is written to both csv files and json.  That seems unnecessary.

**Comment by NullCGT** [comment]
Is this in the most recent version? I removed all the code that writes hashtables to a .csv file a while ago. I just looked through RDataTracker's code and there isn't a trace of my csv writing code left.

**Comment by blernermhc** [comment]
Some of Connor's code is in development but not all of it.  Do we want to merge it all in now so it gets into the upcoming master?  Or we could just remove the code that writes the csv file and not include the other updates for now.

Thoughts?

**Comment by blernermhc** [comment]
Done in a895577
