### ISSUE TITLE
Add PROV-JSON validation testing

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#359]
I've set this as high priority given how important the JSON output is to the functioning of the package and its dependencies. 

From #353. Thomas suggested using this tool for checking http://xmodulo.com/validate-json-command-line-linux.html

**Comment by blernermhc** [comment]
@tfjmp, is this something you can do?

**Comment by tfjmp** [comment]
I am looking at similar things for another project, but it will not be any time soon.

**Comment by blernermhc** [comment]
I have tried to use this json validator starting by first just validating against prov-json syntax as I am expecting our schema to just be additions to that schema, but I am not having success.  I am using the schema from [https://provenance.ecs.soton.ac.uk/prov-json/schema](https://provenance.ecs.soton.ac.uk/prov-json/schema) but I get an error in validation:
```
jsonspec.reference.exceptions.NotFound: u'https://provenance.ecs.soton.ac.uk/prov-json/schema' not registered
```

This seems to be a newer version of the schema linked from the [prov json w3 page](https://www.w3.org/Submission/prov-json/schema), which gives me the same error.

Do you know what this means?  @tfjmp, have you add success using json-spec in your other project?

Here is the complete error message. 

```
-> json validate --schema-file=schema.json < tmp.ddg.json 
Traceback (most recent call last):
  File "/usr/local/bin/json", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/jsonspec/cli.py", line 541, in main
    args.func(args)
  File "/Library/Python/2.7/site-packages/jsonspec/cli.py", line 205, in __call__
    return self.run(args)
  File "/Library/Python/2.7/site-packages/jsonspec/cli.py", line 484, in run
    validated = load(args.schema).validate(args.document)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/draft04.py", line 301, in validate
    obj = validator.validate_all_of(obj, pointer)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/draft04.py", line 357, in validate_all_of
    obj = validator(obj)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/bases.py", line 56, in __call__
    return self.validate(obj, pointer)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/bases.py", line 103, in validate
    return self.validator.validate(obj, pointer)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/bases.py", line 83, in validator
    self._validator = self.context.resolve(self.pointer)
  File "/Library/Python/2.7/site-packages/jsonspec/validators/factorize.py", line 48, in resolve
    return self.factory(self.registry.resolve(pointer),
  File "/Library/Python/2.7/site-packages/jsonspec/reference/bases.py", line 45, in resolve
    obj, fetcher = self.prototype(dp)
  File "/Library/Python/2.7/site-packages/jsonspec/reference/bases.py", line 93, in prototype
    obj = self[dp.document]
  File "/Library/Python/2.7/site-packages/jsonspec/reference/bases.py", line 100, in __getitem__
    raise NotFound('{!r} not registered'.format(uri))
jsonspec.reference.exceptions.NotFound: u'https://provenance.ecs.soton.ac.uk/prov-json/schema' not registered
```

**Comment by blernermhc** [comment]
I tried running the schema validator described in [the same article](http://xmodulo.com/validate-json-command-line-linux.html) on the prov json schema that I downloaded and the schema is fine.  So, I don't understand the error message when I try to use the validator.

**Comment by blernermhc** [comment]
I also tried to use the json-spec validator using an example downloaded from the W3 page and it gives the same reference.exception error.  So, either there is something wrong with W3's schema or with the json-spec validator, but I don't know enough about json to know.  The URL in question show up in the schema as:
```
  "id": "https://provenance.ecs.soton.ac.uk/prov-json/schema#",
```

**Comment by fong22e** [comment]
I am using this [schema](https://www.w3.org/Submission/prov-json/schema) and this [json validator](https://cran.r-project.org/web/packages/jsonvalidate/vignettes/jsonvalidate.html). 

As expected, the validation failed when I first tried it. After more trial and error, it turns out that the problems lie in the `rdt:installedPackages` field of the `environment` node of the `activity` portion of the json file, as well as the `rdt:valType` field of the data nodes in the `entity` portion of the json file. Both contains complex structures that are invalid.

For example, these are invalid:
```
"rdt:installedPackages" : [
	{"package" : "base", "version" : "3.3.3"},
	{"package" : "datasets", "version" : "3.3.3"},
	{"package" : "devtools", "version" : "1.13.2"},
	{"package" : "graphics", "version" : "3.3.3"},
	{"package" : "grDevices", "version" : "3.3.3"},
	{"package" : "jsonlite", "version" : "1.5"},
	{"package" : "methods", "version" : "3.3.3"},
	{"package" : "RDataTracker", "version" : "2.27.0"},
	{"package" : "stats", "version" : "3.3.3"},
	{"package" : "stringi", "version" : "1.1.5"},
	{"package" : "tools", "version" : "3.3.3"},
	{"package" : "utils", "version" : "3.3.3"}]
}
```

```
"rdt:valType" : {"container":"vector", "dimension":[1], "type":["numeric"]},
```
