### ISSUE TITLE
bugs regarding identifying functions and their package of origin

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#360]
When I used `ddg.run` on a file, `Test.R`, which contains a single line, `a <- as.character(c(1:10))`, the following warnings were shown:
```
Warning messages:
1: In .ddg.insert.error.message(error.msg) :
  No binding for .ddg.dev.number . DDG may be incorrect!
2: In .ddg.insert.error.message(error.msg) :
  No procedure node found for Test.R
3: In .ddg.where(name, parent.env(env), warning) : Can't find `<-`
4: In .ddg.where(name, parent.env(env), warning) : Can't find `:`
```
I am most concerned about number 2...

**Comment by MKLau** [comment]
Thanks! @efong22e

Can you grab the RDT version from the session info?

**Comment by fong22e** [comment]
Hey Matt! Where is that information displayed?

@MKLau

**Comment by MKLau** [comment]
@fong22e 

You can use sessionInfo

It's also listed in the RDT json output, but it looks like you can't trust it.

**Comment by fong22e** [comment]
It says `RDataTracker_2.27.0`.
@MKLau

**Comment by MKLau** [comment]
Great, thanks, not particularly helpful. It would be helpful if we had been rolling the thousandths place forward.

**Comment by fong22e** [comment]
I guess... Though we wouldn't have known that these issues would pop up...

**Comment by fong22e** [comment]
It is...working...?

**Comment by MKLau** [comment]
That seems less than enthusiastic. Are your scripts running again?

**Comment by fong22e** [comment]
The scripts that weren't running before are now, but I have no idea what happened. I fiddled with some things and now they work...
