### ISSUE TITLE
Resolve merge conflicts between Hashtable2 and develoment

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#362]

**Comment by erboose** [comment]
Recommend adding the ability to set the hash type in ddg.run before merging to development (or at least before merging to master).  recordR uses MD5, noworkflow uses SHA-1, etc.

**Comment by MKLau** [comment]
Sounds good,  I've created another issue for doing that #363.

**Comment by MKLau** [comment]
I've labeled this as blocked. #363 should be dealt with first.

**Comment by blernermhc** [comment]
Done in a895577
