### ISSUE TITLE
Which hash generator shoud be used? 

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#363]
From @erboose in #362: "Recommend adding the ability to set the hash type in ddg.run before merging to development (or at least before merging to master). recordR uses MD5, noworkflow uses SHA-1, etc." 

@NullCGT had made the decision to use the current hash based on a very practical reason that I have now forgotten. We should contact him to see.

**Comment by erboose** [comment]
@NullCGT switched from MD5 to SHA-1 because noworkflow uses the latter.  But I think we need to be flexible since there is no single hash type in use today.

**Comment by NullCGT** [comment]
@erboose Yeah, that's exactly why! I agree that the flexibility is really important.

**Comment by blernermhc** [comment]
Should we add a hash.function parameter to ddg.run?   What default value?  What allowed values (just MD5 and SHA-1 for now)?

Can we eliminate the save.hashtable parameter?

**Comment by NullCGT** [comment]
I think that's a good idea. I'm guessing that defaulting to MD5 would be good, since I think that's a sort of standard way to hash files. I don't know if I've seen anything commonly used besides MD5 and SHA-1.

I believe that I had save.hashtable in order to make sure that the program passed Travis tests, once we are writing to a database it should no longer be needed.

**Comment by blernermhc** [comment]
I'd like to propose that we handle this as follows:

1. Add a hash.algorithm parameter to ddg.run and ddg.init.  Recognize 2 values for now:  SHA-1 and MD5.  Which should be the default?

2. Add an attribute to the environment, rdt:hashAlgorithm, that records the choice.

3. Change the name of the field in the data nodes from rdt:MD5hash to rdt:hash

@erboose How does that sound?

**Comment by erboose** [comment]
Sounds good to me.  I'd vote for MD5 as the default.

**Comment by blernermhc** [comment]
Implemented in a895577
