### ISSUE TITLE
Error in rbind(deparse.level, ...) 

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#364]
The simple.R script can be found in the *eep-usecases/src/simple*.

I see the following on my laptop (session info follows):

 > source("simple.R")                                      
 > ddg.set.detail(0)                                       
 > ddg.run("simple.R")                                     
 [1] "Saving ddg.txt in ./simple_ddg"                      
 [1] "Saving ddg.json in ./simple_ddg"                     
 [1] "Saving hashtable.csv in .ddg directory."             
 Error in rbind(deparse.level, ...) :                      
   numbers of columns of arguments do not match            
 > ddg.set.detail(1)                                       
 > ddg.run("simple.R")                                     
 [1] "Saving ddg.txt in ./simple_ddg"                      
 [1] "Saving ddg.json in ./simple_ddg"                     
 [1] "Saving hashtable.csv in .ddg directory."             
 Error in rbind(deparse.level, ...) :                      
   numbers of columns of arguments do not match            
 > ddg.set.detail(3)                                       
!> ddg.run("simple.R")                                     
 [1] "Saving ddg.txt in ./simple_ddg"                      
 [1] "Saving ddg.json in ./simple_ddg"                     
 [1] "Saving hashtable.csv in .ddg directory."             
 Error in rbind(deparse.level, ...) :                      
   numbers of columns of arguments do not match            
!> sessionInfo()                                           
 R version 3.4.1 (2017-06-30)                              
 Platform: x86_64-apple-darwin15.6.0 (64-bit)              
 Running under: macOS Sierra 10.12.6

**Comment by blernermhc** [comment]
I do not get that error with your script.  This looks like an error we saw at one point with Connor's code but it has been fixed.  Are you sure you have the latest version of RDT?

**Comment by blernermhc** [comment]
I remember what is happening here.  I bet you have an old hashtable file and the columns changed at one point.  Can you open ~/.ddg/hashtable.csv and confirm that these are the column headers you have:

ScriptPath | FilePath | DDGPath | NodePath | NodeNumber | MD5Hash | ReadWrite | Timestamp | Value

If they are, then I still don't know what is going on.

If they are not, then you should delete the hashtable.csv file and try again.  Run it twice, just to be sure.  The first time will create the csv file and the second time, it should try to update it.

**Comment by blernermhc** [comment]
To add the flexibility that Emery wants for hash numbers, we will need to change this table again.  It should have a hash value column and an algorithm column.

**Comment by erboose** [comment]
At some point we should also add tools to manage the hash table, with an option to delete selected entries.  Otherwise it will continue to grow indefinitely.  The same will be true, I think, for the database.

**Comment by MKLau** [comment]
Sorry, accidently closed this.

**Comment by MKLau** [comment]
So, I deleted the .ddg folder in my home directory and that error goes away. The error doesn't return now. Perhaps it was an old file in that directory. I'm going to close this.
