### ISSUE TITLE
Test on all platforms

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#365]

**Comment by MKLau** [comment]
I've tested on Mac OS and found one bug, issue #364

**Comment by blernermhc** [comment]
Travis does tests on Linux with every push and pull request.  Mac testing happens on Barb's computer when she does updates.  Windows testing is done whenever Elizabeth or Emery make updates.  While it would be nice to automate the Windows and Mac testing, as with Travis, we are getting tests done pretty regularly on all 3 platforms.

**Comment by blernermhc** [comment]
See issue #310 for link describing how to get Travis to test on multiple platforms.

**Comment by blernermhc** [comment]
Travis does the Linux testing.  When we push to master, we will be sure to test on current Mac and Windows platforms ourselves.  Having Travis do all the testing on each commit would take too long.
