### ISSUE TITLE
Create a new workflow for keeping the prov in memory

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#366]
This will help with the efficiency of codecleaning, as currently provenance is written to disk and immediately read back into R. This wouldn't be necessary if the provenance were passed to codecleanR in memory. 

In order to preserve the current workflow of *ddg.run*, we can use a distinct naming convenction for the API user imported functions. Additionally, this will help with the push for CRAN compliance, as it will make writing to disk unecessary for some applications and it will also present a workflow API for users that will conform to the move towward generalizing the function names, e.g., we can use prov as the prefix for functions. 

This relates to codecleanR issue #22 and RDataTracker issue #323.

**Comment by blernermhc** [comment]
prov.json() provides access to the json in memory.
