### ISSUE TITLE
Operators `::` and `:::`

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#370]
For the following commands, `.ddg.where` is unable to find the names `"::, stringr, str_to_upper"` and `":::, stringr, str_to_lower"`
```
stopifnot( identical(stringr::str_to_upper("apple"), "APPLE") )
stopifnot( identical(stringr:::str_to_lower("BAGEL"), "bagel") )
```
I suspect the problem lies with how the names are found in cases where the `::` and `:::` operators are used, and I believe there is more than 1 instance where the parse tree is traversed to find the names.

How often are functions called in this way?

**Comment by blernermhc** [comment]
You shouldn't need to use ddg.where to find the functions in these cases.  The :: and ::: syntax are telling us where the function is:

<package>::<function>

**Comment by fong22e** [comment]
How about in the following case?

```
# user defined function
`pkgA::functionA` <- function()
{
    return(8)
}

`pkgA::functionA`()
```

**Comment by blernermhc** [comment]
Is that legal????

What is the significance of the ` characters?

If that is legal but does not work with our code, I would be happy leaving that as an open issue unless it is trivial to fix.  Nobody should write code that looks like that.

**Comment by fong22e** [comment]
Yes, they are unfortunately all legal.

**Comment by blernermhc** [comment]
Have you tested these cases?  I would think that the parse tree would do the necessary disambiguation so you could tell if the whole thing is a single name, or if it is a package name + function name and so wouldn't actually need any special processing.

The third case has me the most concerned.
```
`pkgC`::`functionC` <- function()
{
    return(10)
}
```
Does this mean that the user is defining a function in a different package???  That would be a problem for us, I think.  The function is being locally defined, so loading the pkgC library would not find the function.

**Comment by fong22e** [comment]
This is what I have so far to capture these edge cases, though it doesn't work on the parse tree for `as.character(c(1:10))`....
```
find.calls.rec <- function( expr )
{
	if( is.call(expr) && ! is.functiondecl(expr) )
	{
		functions <- NULL
		libraries <- NULL
		
		elem1 <- expr[[1]]
		
		# cases `::` and `:::`
		if( is.element(TRUE, grepl("::", expr, fixed=TRUE)) )
		{
			# for cases of expr where parameters to calls are included
			# such as:  utils::as.roman(5)
			if( is.call(elem1) )
			{
				# recuse on all elements of expr
				result <- sapply(expr, find.calls.rec, USE.NAMES=FALSE)
				
				# combine results
				functions <- unlist( mapply(`[`, result, 1) )
				libraries <- unlist( mapply(`[`, result, 2) )
				
			} else
			{
				elem1 <- toString(elem1)
				
				# for the general case of `::` and `:::` usage
				# where expr is, for example:  stringi::stri_join
				if( identical(elem1, "::") || identical(elem1, ":::") )
				{
					functions <- c( toString(expr[[1]]) , toString(expr[[3]]) )
					libraries <- toString(expr[[2]])
					
				} else    # in edge cases where expr is, for example:  `pkgA::functionA`
				{
					# recurse on all elements but first
					result <- sapply(expr[-1], find.calls.rec, USE.NAMES=FALSE)
					
					# combine results
					functions <- unlist( mapply(`[`, result, 1) )
					functions <- append(elem1, functions)
					
					libraries <- unlist( mapply(`[`, result, 2) )
				}
			}
			
		} else    # the general case, such as:  as.character(5)
		{
			# recurse on all elements but first
			result <- sapply(expr[-1], find.calls.rec, USE.NAMES=FALSE)
			print(result)
			
			# combine results
			functions <- unlist( mapply(`[`, result, 1) )
			functions <- append( toString(elem1) , functions )
			
			libraries <- unlist( mapply(`[`, result, 2) )
		}
		
		functions <- unique(functions)
		libraries <- unique(libraries)
		
		return( list(functions, libraries) )
	}
	
	return(NULL)
}
```

**Comment by fong22e** [comment]
I finally got it working! It turns out that the problem I was having was due to R coercing my lists into a matrix or a vector when I wasn't expecting it to so that led to many, many problems...

Thank you so much for your wonderful idea! Using that, I reorganised the code to a structure of this form:
```
if( ! is.call(expr) || is.functiondecl(expr) ) 
{
    return(NULL)
}

if( is.call(expr[[1]]) ) 
{
    // recurse on all parts of expr
} 
else 
{
    if( identical(elem1, "::") || identical(elem1, ":::") ) 
    {
        // case1: elem1 is `::` or `:::`
    } 
    else 
    {
        // general case
    }
}
```
This code, however, fails when the user overwrites the definition of `::` and/or `:::` with their own function.

**Comment by blernermhc** [comment]
You can document that it fails in that case, but I don't think we should worry about that.  That would be such a strange thing for someone to do!
