### ISSUE TITLE
PROV-JSON Compliance

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#373]
This is the [schema](https://www.w3.org/Submission/prov-json/schema) and [validator](http://www.jsonschemavalidator.net/) I used.

I have been trying to make our json files conform to prov-json requirements. I had to change a few things to have it validate against the schema.

---

The first is changing how libraries are represented in the file. They are currently wrapped as an array of objects as part of the `rdt:installedPackages` node under the `activity` property. Unfortunately, this is not allowed. What Barbara ( @blernermhc  )and I came up with was to change that representation to something like the following:

```
"activity" : {
    
    // procedure nodes go here
    
    "environment" : {
        "rdt:name" : "environment",
        "rdt:architecture" : "x86_64",
        "rdt:operatingSystem" : "windows",
        "rdt:language" : "R",
        "rdt:rVersion" : "R version 3.3.3 (2017-03-06)",
        "rdt:script" : "[DIR]/FunctionOriginTest.R",
        "rdt:sourcedScripts" : "",
        "rdt:scriptTimeStamp" : "2017-09-21T20.16.17EDT",
        "rdt:workingDirectory" : "[DIR]",
        "rdt:ddgDirectory" : "[DIR]/ddg",
        "rdt:ddgTimeStamp" : "2017-09-21T20.32.46EDT",
        "rdt:rdatatrackerVersion" : "2.27.0"
    },
    
    "libraries" : {
        "pkg1" : [
            {
                "$" : "stringi",
                "type" : "xsd:QName"
            },
            {
                "$" : "1.1.5",
                "type" : "rdt:version"
            }
        ],
        "pkg2" : [
            {
                "$" : "stringr",
                "type" : "xsd:QName"
            },
            {
                "$" : "1.2.0",
                "type" : "rdt:version"
            }
        ]
    }
}
```
What this does is that the libraries are grouped together under a property on the same level as the `environment` property. The structure for each package is an array of PROV literal values, which is one of 2 ways I could think of to have a PROV-JSON compliant group of things at this level of nesting.

Alternatively, since they are both strings, we could use an array of strings to represent each package instead. For example:

```
"libraries" : {
    "pkg1" : ["stringi","1.1.5"],
    "pkg2" : ["stringr","1.2.0"]
}
```

This method, however, does not allow us to specify what each item in the array is.

Another question is whether or not the `libraries` and `environment` properties fall under the `activity` property. They could also be put under the `entity` property, but this is more of a design choice.

---

`ValType` has a similar problem in terms of PROV-JSON compliance, where it is a complex object put under a property in a data node, wrapped under `entity`. This is one method I came up with to get around this problem:

```
"entity" : {

    // data nodes go here

    "d20" : {
        "rdt:name" : "fn4",
        "rdt:value" : "#ddg.function",
        "rdt:type" : "Data",
        "rdt:scope" : "R_GlobalEnv",
        "rdt:fromEnv" : "FALSE",
        "rdt:MD5hash" : "",
        "rdt:timestamp" : "",
        "rdt:location" : ""
    },

    "d21" : {
        "rdt:name" : "f",
        "rdt:value" : "20",
        "rdt:type" : "Data",
        "rdt:scope" : "0x0000000015fdc4e0",
        "rdt:fromEnv" : "FALSE",
        "rdt:MD5hash" : "",
        "rdt:timestamp" : "",
        "rdt:location" : ""
    } ,
    
    "ValTypes" : {
        "t20" : [
            {
                "$" : "d20",
                "type" : "rdt:associatedWith"
            },
            {
                "$" : "vector",
                "type" : "rdt:container"
            },
            {
                "$" :  "[1]",
                "type" : "rdt:dimension"
            },
            {
                "$" : "[\"character\"]",
                "type" : "rdt:type"
            }
        ],
        "t21" : [
            {
                "$" : "d21",
                "type" : "rdt:associatedWith"
            },
            {
                "$" : "vector",
                "type" : "rdt:container"
            },
            {
                "$" :  "[1]",
                "type" : "rdt:dimension"
            },
            {
                "$" : "[\"numeric\"]",
                "type" : "rdt:type"
            }
        ]
    }
}
```

In a manner similar to the installed libraries, we group each `ValType` into its own node and have each type say which node it is associated with. The values in arrays for `rdt:dimension` and `rdt:type` are also in quotes to turn them into strings as arrays in literals such as these are not allowed.

And since all 3 values are technically strings, we could also simply put the strings into an array directly. For example:

```
"ValTypes" : {
    "t20" : [
        "d20",
        "vector",
        "[1]",
        "[\"character\"]"
    ],
    "t21" : [
        "d21",
        "vector",
        "[1]",
        "[\"numeric\"]"
    ]
}
```

Alternatively, we could convert the entire complex structure for `ValType` into a string and still have it put under each data node. For example:

```
"activity" : {

    // data nodes go here

    "d20" : {
        "rdt:name" : "fn4",
        "rdt:value" : "#ddg.function",
        "rdt:valType" : "{
            \"container\":\"vector\", 
            \"dimension\":[1], 
            \"type\":[\"character\"]
        }",
        "rdt:type" : "Data",
        "rdt:scope" : "R_GlobalEnv",
        "rdt:fromEnv" : "FALSE",
        "rdt:MD5hash" : "",
        "rdt:timestamp" : "",
        "rdt:location" : ""
    },
}
```

---

Thankfully, the information about functions called and the packages they are from is far easier to make PROV-JSON compliant. It is currently like this:

```
"activity" : {

    // procedure nodes go here

    "p8" : {
        "rdt:name" : "stopifnot(as.numeric(stri_flatten(stri_sort(stri_trim(stri_r",
        "rdt:type" : "Operation",
        "rdt:elapsedTime" : "0.629999999999995",
        "rdt:scriptNum" : "0",
        "rdt:startLine" : "36",
        "rdt:startCol" : "1",
        "rdt:endLine" : "42",
        "rdt:endCol" : "13",
        "rdt:functionsCalled" : ["stri_flatten","stri_sort","stri_trim","stri_reverse","str_to_lower","str_to_upper"],
        "rdt:packagesUsed" : ["stringi","stringr"]
    } 
}
```

This information is listed as 2 separate properties in each node. Should they be wrapped together? If so, as they are both lists, there would be the same problem as `libraries` and `ValType`. How should we get around that?

---

Thank you for reading! Please help!

**Comment by tfjmp** [comment]
See from July 2016:
https://github.com/End-to-end-provenance/RDataTracker/issues/138

**Comment by fong22e** [comment]
Thank you!

**Comment by tfjmp** [comment]
My understanding of the problem, is ProvJSON does not support attributes that are themselves JSON objects? Is that a fair summary of the issue?

My two cents on your proposal:

I would make each library an independent node, rather than grouping them under a library entry. I would tend to think of library as entity, but it can go both way, so not much of an opinion there.

The ValType proposition don't look ideal to me, there must be some better alternative.

Finally, the function/library thing. You lose the relationship between functions and their libraries.  Representing things as a graph may solve the problem.

**Comment by fong22e** [comment]
Thank you so much for responding and for your ideas, Thomas! I think that this is a better summary of the issue:

![provjsonproblem](https://user-images.githubusercontent.com/20979904/31293072-ddc939b0-aaa3-11e7-86a7-9ab751fd6669.png)

---

Regarding the libraries, would this be an example of what you mean?

```
"entity" : {
    
    // data nodes here
    
    "environment" : {
        "rdt:name" : "environment",
        "rdt:architecture" : "x86_64",
        "rdt:operatingSystem" : "unix",
        "rdt:language" : "R",
        "rdt:rVersion" : "R version 3.3.3 (2017-03-06)",
        "rdt:script" : "[DIR]/ddg",
        "rdt:sourcedScripts" : "",
        "rdt:scriptTimeStamp" : "2017-08-01T15.12.55EDT",
        "rdt:workingDirectory" : "[DIR]",
        "rdt:ddgDirectory" : "[DIR]/ddg",
        "rdt:ddgTimeStamp" : "2017-08-01T15.20.00EDT",
        "rdt:rdatatrackerVersion" : "2.26.2"
    },
    
    "installedPackage1" : {
        "package" : "base",
        "version" : "3.3.3"
    },

    "installedPackage2" : {
        "package" : "datasets",
        "version" : "3.3.3"
    }
}
```
I still feel like it would be best if the libraries themselves are at least wrapped in the same location as the environment node, as I feel that it is part of the environment.

Does anyone else have a thought on if this should be moved to the `entity` node or kept in `activity`?

---

Regarding ValType, given the constraints that the PROV-JSON schema puts on the file, I am really out of ideas as to how else I can represent it better. Do you have suggestions or ideas?

---

About the function/library thing, would you prefer map each function called to what library it is from? For example:

```
"activity" : {

    // other activities

    "p5" : {

        // other properties of a procedure node

        "functions" : [
            { "name" : "stri_flatten", "library" : "stringi" },
            { "name" : "stri_sort", "library" : "stringi" },
            { "name" : "stri_reverse", "library" : "stringi" },
            { "name" : "stri_trim", "library" : "stringi" }
        ]
    }
}
```
However, this, similar to the libraries' original implementation, is not PROV-JSON compliant. The schema does not allow for arrays of objects in any level of nesting.
