### ISSUE TITLE
Finding function calls - when a function name is passed in as a parameter

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#380]
In cases such as `lapply(expr, find.calls)`, where a function name is passed in as a parameter, the type of the node that contains the function name that is passed in (`find.calls` in this case), is the same as variable names that can also be passed in as a parameter.

In the case of `lapply(expr, find.calls)`, `expr` is the variable name of an object (the parse tree in this case) and `find.calls` is the name of a function to be applied to all elements of `expr`. When checking the types, the `typeof()` and `class()` functions return `symbol` and `name` for both `expr` and `find.calls`.

Is there a way to differentiate between normal variable names and names of those that contain functions, or should this be done in run-time instead?

**Comment by blernermhc** [comment]
This would need to be checked at runtime.  Since R is an untyped language, there would be no way to tell statically.
