### ISSUE TITLE
Writing to file from within a function

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#385]
Writing to file from within a function is not captured correctly.  In the following example:

f <- function() {
     st <- "The quick brown fox jumped over the lazy dog"
     outfile <- file("test.dat", "w")
     writeLines(st, outfile)
     close(outfile)
}

f()

When provenance inside functions is turned off, the output file is not captured in the DDG.  When it is turned on, an output file node is connected to the close statement inside the function and a second output file node is connected to the end node for the script.

**Comment by blernermhc** [comment]
Using trace as proposed in issue 289 would solve this problem.

**Comment by blernermhc** [comment]
Fixed when I/O tracing was added.
