### ISSUE TITLE
Assigning a global variable inside a function

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#386]
Assignment of a global variable inside a function is not captured correctly when provenance inside functions is turned off.  In the following example:

g <- function(x) {
     y <<- x^2
     return(y)
}

a <- g(10)
b <- 2*y

If provenance inside functions is turned off, the DDG does not capture the global assignment and the variable is later shown incorrectly as coming from the environment.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/ce1cfa2e756cf993a6a28943df0b5919c5b36724
