### ISSUE TITLE
Data node d1 is the name of script when ddg.run is called by another function

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#405]
When RDataTracker is run on a script, the first data node produced is the name of the script. It has an edge to procedure node p2. This only occurs when ddg.run is called by another function. 
For example, it occurred when tested with this:
```{r}
test <- function() {
  ddg.run("testScript.R")
}
test()
```

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/6004379476c303303d8d5b423d777f8ab29dcd91
