### ISSUE TITLE
For provDebugR: if error occurs inside of sourced script no finish nodes created

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#426]
This issue effects provDebugR and DDG Explorer. 
This is triggered if RDataTracker is run a script that sources another script, and the sourced script has an error in it. In the provenance, no "Finish" procedure nodes are created to indicate where the end of the sourced scripts occur. Without the "Finish" nodes it appears we are unable to determine with certainty how to "collapse" code in scripts.

This can be viewed with the following scripts,
testScript.R
```{r}
x <- 1
a <- 5
source("~/Desktop/test2.R")
y <- 9
```
test2.R
```{r}
source("~/Desktop/test3.R")
print("This is test2")
source.test <- 4359
```
test3.R
```{r}
print("This is test3")
source3.test <- b * 2
```
'b' is not defined in test3.R and will cause an error to occur when ddg.run is called on testScript.R or test2.R.

The end of the resulting procedure nodes in provenance looks as follows,
```{json}
"rdt:p7": {
	"rdt:name": "source3.test <- b * 2",
	"rdt:type": "Operation",
	"rdt:elapsedTime": 51.281,
	"rdt:scriptNum": 2,
	"rdt:startLine": 3,
	"rdt:startCol": 1,
	"rdt:endLine": 3,
	"rdt:endCol": 21
},
"rdt:p8": {
	"rdt:name": "source(\"~/Desktop/test3.R\")",
	"rdt:type": "Operation",
	"rdt:elapsedTime": 51.287,
	"rdt:scriptNum": 1,
	"rdt:startLine": 1,
	"rdt:startCol": 1,
	"rdt:endLine": 1,
	"rdt:endCol": 27
},
"rdt:p9": {
	"rdt:name": "source(\"~/Desktop/test2.R\")",
	"rdt:type": "Operation",
	"rdt:elapsedTime": 51.297,
	"rdt:scriptNum": 0,
	"rdt:startLine": 4,
	"rdt:startCol": 1,
	"rdt:endLine": 4,
	"rdt:endCol": 27
}
```

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/30d351173b1c6ad8fa43cd64d3c08dabd4821f38
