### ISSUE TITLE
Provenance graph not saved in console mode on Windows 10

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#431]
Running RDataTracker in console mode on Windows 10 generates the following warning:

In .ddg.insert.error.message(error.msg) :
  Part of history is missing. DDG may be incomplete! Tried reading from c:/Prov/prov_console/data/.ddghistory but could not find timestamp: ##-ddg-- Thu Jul 19 15:24:03 2018 ------##

The history file (.ddghistory) is created but the file is empty.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/e3ef5935ddb2a7c04f9889515ba5c88d70532850

We no longer use the history file to implement console mode.  We now use the task callback functionality.
