### ISSUE TITLE
Add collection tool settings to provenance graph

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#435]
The agent field of the prov-json string currently stores the name of the provenance collection tool, the tool version number, and the json version number.  For later use, it might be helpful to add collection tool settings that determined what provenance was collected.  This information might vary by tool and language.  For RDataTracker, for example, it might include whether snapshots were stored (and maximum size, if any), whether provenance was collected inside functions, whether provenance was collected inside control constructs, and whether provenance was collected inside loops (and associated constraints, if any).

**Comment by blernermhc** [comment]
That sounds like a good idea.  I think that information should go in the environment node.  It would be reasonable for the environment node to be a depository for any information of this type of global nature that a tool might want to record.

**Comment by fong22e** [comment]
Aside from `prov.run`, which other functions should I keep track of its arguments for? `prov.init` perhaps?

**Comment by blernermhc** [comment]
I think prov.run and prov.init is sufficient.
