### ISSUE TITLE
parent.frame and getting the environment

### ISSUE THREAD

**Issue by kandluis** [End-to-end-provenance/RDataTracker#44]
This has yet to cause issues, but it might. We often make calls like the following to get the environment under which the current definition occurs for a variable.
```
x <- parent.frame()
```
However, the documentation states the following:
Beware of the effect of lazy evaluation: these two functions look at the call stack at the time they are evaluated, not at the time they are called. Passing calls to them as function arguments is unlikely to be a good idea.

Should we use 
```
x <- force(parent.frame())
```
? How would that effect the results?

**Comment by blernermhc** [comment]
We should investigate this further.  The place where I think this may come up is using higher-order functions, like sapply.  If the function that is being applied references variables from the environment in which it is declared, does that work??

**Comment by blernermhc** [comment]
This seems to be addressed now.  Higher-order functions get the bindings correct.
