### ISSUE TITLE
Should value of a function in the prov json be '#ddg.function'?

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#442]

**Comment by blernermhc** [comment]
In the version that I am working on now, if no snapshots are being saved, the value in the node will be the first line of the function.  If snapshots are being saved, the snapshot is an R file containing just that function.

Does this seem like a reasonable solution?

**Comment by blernermhc** [comment]
The value of a function node is now the source code of the function if snapshots are being saved.  If snapshots are not being saved, the first line of the function is saved in the node.

There is a remaining issue #471
