### ISSUE TITLE
How should factors be handled?

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#443]
Currently factors are just saved with the valType of 'object' and a text file with some string representation. Data is lost if we want to reconstruct a script (using provDebugR for example). Possibly may be able to save them as .RObjects, like we do with lists? Also is an issue if a data.frame has a column of factors, and may need to be handled differently.

**Comment by blernermhc** [comment]
We should reconsider what we put in snapshot files.  It seems objects would be more useful for the debugger, and probably other R provenance tools.

Is there a way that we could read R Objects from Java so that DDG Explorer could still display them?

**Comment by blernermhc** [comment]
Snapshot files are now written out as both .RObject files and .txt files.

The string version of factors is more meaningful, as well.

Implemented in https://github.com/End-to-end-provenance/RDataTracker/commit/294fba51143461b66c4aee0d9e57be3c683a8074
