### ISSUE TITLE
Identify input & output files in prov-json string

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#456]
Since we now know when a file is read from or written to, and this information is included in the data nodes table in the ddg.rw column, it would be useful to add this information as a new field for data nodes in the prov-json string, where it could be queried directly without having to inspect input and output edges.

**Comment by blernermhc** [comment]
We are investigating whether doing this via the parser instead of modifying the json is a better solution.

**Comment by blernermhc** [comment]
The parser has separate functions to get input files and get output files.
