### ISSUE TITLE
Error when prov.json is run before prov.run

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#458]
There should be a warning from prov.json instead.  Here is what currently happens:

```
> prov.json()
Error in if (pkg == "base") file.path(.Library, "base") else if (isNamespaceLoaded(pkg)) getNamespaceInfo(pkg,  : 
  argument is of length zero
In addition: Warning message:
In .ddg.insert.error.message(error.msg) :
  No binding for ddg.tool.name . DDG may be incorrect!
```

**Comment by fong22e** [comment]
A warning or an error? Would you prefer I form a "blank" json similar to when `prov.run` is called on a blank file, or would you prefer that the program just stops?

**Comment by blernermhc** [comment]
A warning would be good and it should return NULL.

prov.json is also called from tools, like prov.visualize so it would be good for prov.visualize to be able to test for NULL instead of just failing.

**Comment by erboose** [comment]
If no provenance graph is available, prov.json displays the message "No provenance graph is available" and returns NULL.
