### ISSUE TITLE
Using ddg.procedure to annotate steps within a function

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#46]
It should be possible to use ddg.procedure to annotate steps within a function. However use of the ins parameter to refer to a local variable may lead to a "data node not found for local variable" error.  The error can be removed by supplying a data node with ddg.data within the function, but since the data node is local, data edges to variables outside the function may not be drawn correctly.

**Comment by blernermhc** [comment]
I am not sure what this issue means.  Emery, is this still an issue or has it been resolved?

**Comment by blernermhc** [comment]
This was related to manual annotation, which we no longer use.
