### ISSUE TITLE
print.value[[2]] error

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#480]
In the following code:
```
a <- 1
write(a, "a.csv")
b <- read.table("a.csv")
```
When using prov.run, the following error is produced:
```
<simpleError in print.value[[2]]: subscript out of bounds>
```
On further investigation, it seems like this error is from `.ddg.get.node.val`, in `DataNodes.R`, in the first nested if block. I am guessing it has to do with how the data value that is passed into `.ddg.get.node.val` is created, but I am not sure.

I am working on the `filenodes` branch.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/62f372ac9f21ab8cd53975611e59c62d1e5fb9ad
