### ISSUE TITLE
save.debug parameter in prov.run

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#481]
When `save.debug = TRUE` in wile using prov.run, the annotated script is shown in the provenance graph as an additional data node. I thought we fixed this bug some time ago but it seems to have resurfaced. I unfortunately do not remember how it was fixed...

I am on the `filenodes` branch.

**Comment by blernermhc** [comment]
I have the fix and will be pushing it shortly.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/3e195c7aae96531d8a7b4169095b629c30d5e119
