### ISSUE TITLE
FileNodesTest

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#482]
In the following section in `FileNodesTest.R`:
```
# Pipe input
file.in <- pipe ("cat foo.txt")
df <- readLines(file.in)
close (file.in)
print(df)
```
The value printed by the print function is `character(0)`. I don't think that is correct, but I am not sure on how to fix it. I would like to add this test to our regression tests.

**Comment by blernermhc** [comment]
Can you try running this code without prov.run, just straight-up R code.  I think you will get that same output if "cat foo.txt" fails, which maybe it does on Windows.  

We should use something  that will work on all platforms, or use an if-statement to run different commands on different platforms.

**Comment by blernermhc** [comment]
For now the pipe test is commented out, meaning that the pipe function is not being tested.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/fc45f9047e6da32daf0004c0b96a4ececbdb148a

The pipe test is now running with a command available on Mac, Linux and Windows.
