### ISSUE TITLE
Rename ddg json fields

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#486]
We should rename ddgDirectory and ddgTimestamp to be provDirectory and provTimestamp in the JSON.

**Comment by erboose** [comment]
And update url for "rdt" prefix to point to Elizabeth's JSON document.

**Comment by fong22e** [comment]
Hi Emery ( @erboose ), which link to the JSON document would you like me to use? As in, should it point to this repository, the provR public-facing repository, or RDT's public-facing library?

**Comment by erboose** [comment]
Hi Elizabeth--That's a good question that we might pose to the larger group.  Whatever we put there will persist in the JSON files.  Not sure whether to recommend one of our GitHub pages, or a dedicated web page, or possibly even a DOI.  What do folks think?

**Comment by erboose** [comment]
If we use a GitHub repo, I suggest using the original End-to-end-provenance/RDataTracker repo since it may be more stable over time than the two derivative RDT and provR repos.

**Comment by fong22e** [comment]
The rdt prefix will have this link here: 
[https://github.com/End-to-end-provenance/RDataTracker/blob/master/JSON-format.md](https://github.com/End-to-end-provenance/RDataTracker/blob/master/JSON-format.md)

Is that ok?

**Comment by blernermhc** [comment]
That's the right document but I think we will probably want it to show up with a different URL, probably something on the provtools.org website.  Emery and I are working on a plan about how to organize the 2 github organizations (provtools and end-to-end-provenance) which should help us answer this question.

**Comment by fong22e** [comment]
I will change it to this link, now that the document is in its own repository:
[https://github.com/End-to-end-provenance/ExtendedProvJson/blob/master/JSON-format.md](https://github.com/End-to-end-provenance/ExtendedProvJson/blob/master/JSON-format.md)
