### ISSUE TITLE
Source script while in console mode?

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#487]
The prov.source function is currently prohibited in console mode.  We might experiment with removing this restriction and testing to see if it is possible to use prov.init, prov.source, and prov.quit; in other words, to source a script during a console session.  Is this something we want to support?

**Comment by blernermhc** [comment]
I just tried removing this restriction and it works fine.  I don't see any reason not to allow this.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/ee4f6f9e03cc7899687e8c5cce73af46e903295b
