### ISSUE TITLE
SourceFunc and timestamps not recorded

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#504]
For some reason, the SourceFunc tests are failing. After investigating it more, I found out that it is because the timestamps for each individual sourced script is not recorded in the json file.  I am not having this problem for either rdt or rdtLite when run in RStudio, only when it is run in ant. I am guessing that is could be related to the new structure for the scriptTests directory, but I am not sure.

This code is in the provRtests branch.

**Comment by blernermhc** [comment]
The expected results don't even have a section to hold the timestamps.

The new results have the section but all the values are null.

**Comment by fong22e** [comment]
Yes, I have not updated the expected results for those tests on the provRtests branch. The null values in the new results are what is causing prov-json compliance testing to fail.

**Comment by blernermhc** [comment]
I have pushed a fix to this on the provRtests branch.  The path to the sourced script was being ignored when its timestamp was looked up.  

Fixed in  92133af

**Comment by fong22e** [comment]
Thank you Barbara!
