### ISSUE TITLE
install-and-test

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#505]
`install-and-test` is the default target for the tests.xml file. I am planning on implementing a version for rdt and another for rdtLite. However, which prov collection tool should `install-and-test` default to? I am thinking rdtLite as it is our CRAN version and what the other targets in the file default to. Would that be best?

Additionally, `install-and-test` also runs the target `test-all` for testing. Would it be better to use the `test-travis` target instead? I am thinking that it may be better since we will be able to find out if it fails or not without having to dig through the entire log.

**Comment by blernermhc** [comment]
Does install-and-test run install from the build xml?  I hadn't remembered that.

I agree that switching it use test-travis instead of test-all would be good.

**Comment by fong22e** [comment]
Which test-travis target? rdt or rdtLite?

**Comment by blernermhc** [comment]
Does anybody use install-and-test?  It doesn't look like it actually does an installation.  I think we should get rid of it and make one of the test-travis targets be the default.  I am indifferent about which one.

**Comment by fong22e** [comment]
I definitely don't use it and I am in favour of removing it.

**Comment by fong22e** [comment]
I am changing it to `test-travis-rdtLite`.
