### ISSUE TITLE
Summary level collection

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#516]
Add a parameter to prov.run that allows collection of just environment, input/output files & URLs, and random numbers.

**Comment by erboose** [comment]
Note that errors and warnings are not recorded when details=FALSE.  In that case we'll want to suppress the ERRORS report in provSummarizeR (which otherwise will report no errors found).  One way to do this would be to add the provenance collection tool settings to the JSON file (see issue 435).

**Comment by erboose** [comment]
Alternatively, error messages could be recorded even when details=FALSE.  The express branch has been updated to do this.

**Comment by blernermhc** [comment]
This looks good!  I think you should also catch warnings like ddg.parse.commands does.

**Comment by erboose** [comment]
Agreed.  Note that (with this simplified approach) we won't have the script name or line number to go with the error or warning message.  If that's Ok, we could update provSummarizeR to simply list any error and warning messages in such cases.

**Comment by blernermhc** [comment]
I think that is a good idea.

**Comment by blernermhc** [comment]
I updated provSummarizeR for this case.  It now just displays the error message without script name or line number.

**Comment by blernermhc** [comment]
Closing this since the details parameter does most of this.  Issue #101 is open and is about random numbers.
