### ISSUE TITLE
Problem with installing RDataTracker by using devtools::install_github()

### ISSUE THREAD

**Issue by LudwigEnglbrecht** [End-to-end-provenance/RDataTracker#521]
I would like to install the **RDataTracker** package with **install_github()**. Usually this method works very well. Only during this installation by using 
`devtools::install_github('End-to-end-provenance/RDataTracker', ref='development', force=TRUE)` 
I always get the following error:

`Error: HTTP error 404. Not Found`

I am using version 3.5.1 of R and the OS: Windows 10, 64 Bit. I also tried to install the _master_ branch. This led to the same error. Unfortunately I don't get any more information from R what could be connected with the error. I would be grateful for any help.

![r](https://user-images.githubusercontent.com/11033556/49701536-00435100-fbee-11e8-920f-ac8889947aba.png)

**Comment by erboose** [comment]
The RDataTracker repository now contains the code for two different versions of our provenance tool, rdt and rdtLite.  For more information on these tools and how to install them from GitHub, as well as related applications that use the resulting provenance, please see:
     
https://github.com/End-to-end-provenance/End-to-end-provenance.github.io/blob/master/RTools.md

rdtLite is also now available on CRAN.

**Comment by blernermhc** [comment]
Thanks for your interest in RDataTracker!  Following up on Emery's response, I would suggest that you install rdtLite, which is a more stable version of our R provenance tool.  You can install it either using 

```
install_github("End-to-end-provenance/rdtLite")
```

or you can install it directly from CRAN.  

Please let us know if you have any problems with the installation of rdtLite.

**Comment by LudwigEnglbrecht** [comment]
Many thanks for the helpful answers! 
I was able to solve the problem with `install.packages("rdtLite")`. Also the installation via `devtools::install_github("End-to-end-provenance/rdtLite")` worked.

**Comment by blernermhc** [comment]
Thanks for letting us know!
