### ISSUE TITLE
Function to procedure edges missing

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#526]
On the latest version development, I noticed that function to procedure edges are missing. For example, in the test Return, I get the following ddg:
![error](https://user-images.githubusercontent.com/20979904/50940559-628eac00-144f-11e9-9721-89486fa0faa2.png)
I am pretty sure there should be edges flowing from the function data nodes to where they are used and I am not sure what happened to cause them to disappear.

**Comment by fong22e** [comment]
Unfortunately, in the latest version of development, those edges are missing in rdt as well. I tried it just now.

**Comment by erboose** [comment]
Looks like the edges are missing in the CRAN version of rdtLite as well.

If I recall correctly, this problem came up once before and was solved.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/pull/527/commits/cb6781fe621bd3712f4064cb811cdd9bbd41435c
