### ISSUE TITLE
No hash values for urls

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#537]
URL nodes do not have a hash value.  We save a copy of the downloaded data in the data folder.  It would be good to calculate the hash value and put that in the provenance node, especially since the contents of a url would be susceptible to change.

**Comment by erboose** [comment]
Is the hash value affected by the user's operating system and browser?  Text files, for example, have different end of line characters in Windows and Unix.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/pull/545/commits/ea5cc4e9bae39351a715588ba010f1b270982c08

There is no problem with line endings.
