### ISSUE TITLE
Assigning variables to global - extra data node

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#551]
[rdtLite]
In the following case:
```
fn9 <- function()
{
  fn <- function()
  {
    p <<- 19
    stopifnot( p == 19 )
  }

  fn()
  stopifnot( p == 19 )
}

fn9()
stopifnot( p == 19 )
```
There is an additional node in the ddg. This is indicated by the black circle.
![fn9](https://user-images.githubusercontent.com/20979904/61396877-ac40cf00-a896-11e9-8279-c04f2b0a757f.png)

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/pull/555/commits/b4f6ac983f24a700971a02ad2daddfd59e6f8fa7
