### ISSUE TITLE
Error when creating a matrix

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#560]
When the following is run with `rdtLite` or `rdt`,
```
a <- matrix(c(1:10),10,10)
```
The following error is produced:
```
<simpleError in if (grepl("\n", print.value)) {    print.value <- paste0(sub("\\n.*", "", print.value), "...")}: argument is of length zero>
```
There is no traceback available. The expected matrix does get produced and this code runs fine (no error) when run in RStudio.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/aae198bd9b4d93a083414d295429fab83a29d38b.
