### ISSUE TITLE
Consider having prov.run report concerns to the user

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#591]
Examples of things we might report:
1. Using a value defined prior to script execution
2. Attach line numbers to warning messages

**Comment by fong22e** [comment]
rdt and rdtLite does this when a variable name (originally a function) is redefined by another function. For example:
```
f <- function(x)
{
    return(x)
}

print(f(1))

f <- function(x)
{
    return(x+1)
}

print(f(2))
```
Will give the following warning message.
```
Warning message:
In .ddg.save.func.decl.info(.Object@parsed[[1]][[2]], .Object@parsed[[1]][[3]]) :
  Multiple functions defined with name f .  Provenance about use of non-locals inside these functions may be incorrect.
```
I was looking into fixing this today but I just remembered Aaron pointed out a few meetings ago that redefining variables (any variables, not just functions) would be the first thing he would warn users about.

**Comment by blernermhc** [comment]
We now have provAnalyzeR that does these kinds of checks.
