### ISSUE TITLE
Line numbers in console mode

### ISSUE THREAD

**Issue by fong22e** [End-to-end-provenance/RDataTracker#612]
I noticed that when in console mode, line and column numbers, as well as script numbers are recorded as -1. This makes it impossible for functions in the debugger that query by line and/or script numbers (most of them) to function.

**Comment by blernermhc** [comment]
Implemented in https://github.com/End-to-end-provenance/RDataTracker/commit/f6e2e541481897fca1b22b9de69e74743baebf7d
