### ISSUE TITLE
Add hash values of main & sourced R script files

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#618]
Recording the hash values of the main R script (and any sourced scripts) would make it easier to uniquely identify the script.  In Windows, at least, it's possible to update a file without changing its date-time stamp.  The hash values could be added to the environment section of the JSON file.

**Comment by blernermhc** [comment]
Implemented in 45a3bc4e51238ab26eee6eb28f6fb0e43a9005a5
