### ISSUE TITLE
Improve support for recording console sessions

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#619]
A complete transcript of the commands issued in a console session would help support clarity and reproducibility.  This could be assembled at the parser level, but commands are currently truncated in the JSON file since they are used primarily as names of procedure nodes.  It might be worth evaluating the pros and cons of recording the full commands in the JSON file.

**Comment by blernermhc** [comment]
Implemented in https://github.com/End-to-end-provenance/RDataTracker/commit/f6e2e541481897fca1b22b9de69e74743baebf7d
