### ISSUE TITLE
Drug Mentions Music

### ISSUE THREAD

**Issue by Ranjanirr** [End-to-end-provenance/RDataTracker#628]
setwd("~/Documents/DataCollection/DrugMentions")
> library (rdtLite)
> prov.init("DrugsinMusic.R", prov.dir = ".", overwrite = FALSE)
> library(tidyverse)
── Attaching packages ─────────────────────────────────────────────── tidyverse 1.3.0 ──
✓ tibble  2.1.3     ✓ purrr   0.3.3
✓ tidyr   1.0.2     ✓ stringr 1.4.0
✓ readr   1.3.1     ✓ forcats 0.5.0
── Conflicts ────────────────────────────────────────────────── tidyverse_conflicts() ──
x psych::%+%()         masks ggplot2::%+%()
x psych::alpha()       masks scales::alpha(), ggplot2::alpha()
x readr::col_factor()  masks scales::col_factor()
x gridExtra::combine() masks dplyr::combine()
x purrr::discard()     masks scales::discard()
x dplyr::filter()      masks stats::filter()
x dplyr::lag()         masks stats::lag()
> library(tidytext)
> data <- read.csv('billboard_lyrics_1964-2015.csv') %>% filter(!is.na(Lyrics))
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> data <- data %>% arrange(Lyrics) %>% .[-(1:47),] %>% arrange(Year) # this was the fastest way to remove songs with " " or "  " lyrics
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> data[] <- data %>% lapply(as.character) # https://stackoverflow.com/questions/2851015/convert-data-frame-columns-from-factors-to-characters
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> all_drugs <- c('blunt','toke','marijuana','weed','bong','drug','drugs','coke','molly','cocaine','doobie',
+                'vicodin','marijuana','pills','pill','heroin', 'crack','percocet', 'acid')
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> all_drugs_count <- data %>% 
+   unnest_tokens(word, Lyrics) %>% 
+   group_by(Year) %>% 
+   count(word, sort=T) %>% 
+   filter(word %in% all_drugs) %>% 
+   summarize(all=n())
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> all_drugs_count$Year <- as.numeric(all_drugs_count$Year)
<simpleError in snapshot.size * 1024: non-numeric argument to binary operator>
> 
> all_drugs_count %>% 
+   complete(Year=seq(1965,2015,1)) %>%  
+   ggplot(aes(Year,all)) + geom_bar(stat='identity')
Warning message:
Removed 9 rows containing missing values (position_stack). 
Error in snapshot.size * 1024 : non-numeric argument to binary operator
> prov.quit()
[1] "Saving prov.json in /Users/ranjaniramanathan/Documents/DataCollection/DrugMentions/prov_console_2020-06-02T23.41.27EDT"
> prov.summarize(save = TRUE, create.zip = FALSE)

**Comment by Ranjanirr** [comment]
Where it came from: Kaggle = Drug mentions in popular music

**Comment by blernermhc** [comment]
prov.init should not be passed the script name as a parameter.  That argument is getting bound to the snapshot.size parameter, which leads to the problem.
