### ISSUE TITLE
Add Graphics Node Error when executed on script that uses colorblindr

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#630]
When a package like colorblindr edits a ggplot, it causes the following error to stop provenance collection when using rdtLite:
```
Error in if (.ddg.is.set("ddg.last.graphics.file") && .ddg.get("ddg.last.graphics.file") !=  : 
  missing value where TRUE/FALSE needed
```
Some simple debugging showed that .ddg.is.set("ddg.last.graphics.file") is returning True. But, in .ddg.get("ddg.last.graphics.file"), when "ddg.last.graphics.file" is grabbed from the ddg.env its value is NULL. 

The simplest script to reproduce this bug is here:
```{r}
library(ggplot2)
library(colorblindr)  # devtools::install_github("clauswilke/colorblindr")

# May also need to install colorspace
# install.packages("colorspace", repos = "http://R-Forge.R-project.org") --- colorblindr requires the development version

test <- ggplot(data = mtcars)
test <- edit_colors(test , desaturate)

ggsave(paste0(tempdir(), "test.pdf"))
```

In this script, if the line `test <- edit_colors(test , desaturate)` is commented out then provenance collection works as it should. 

Versions used in this issue:
R 3.6.1
rdtLite 1.2.1 (CRAN version and Development version tested)
ggplot 3.3.0
colorblindr 0.1.0 (installed from GitHub)
colorspace 1.4-2

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/pull/631/commits/4f82db00fa41626a340f0050ee8c41495490c6d2
