### ISSUE TITLE
Error in .ddg.get.node.val when dealing with complex array

### ISSUE THREAD

**Issue by jwons** [End-to-end-provenance/RDataTracker#635]
When dealing with a complex array, rdtLite will encounter an error in the .ddg.get.node.val function. 

I have written a simple test script that will produce the error, the only package needed is rdtLite and it doesn't need to read in any data.
```{r}
# Creation of array
n <- c("foo", "bar", "bat")
z <- c("hello", "world,","R","is","fun",".", "Watch out", "for","the R", "Inferno")

# First instance of error
# Error won't stop script
complex.array <- array(NA,c(2,length(n),length(z)), dimnames=list(c("1998","1999"),n,z))
print("Will display simple error before this, so this will print")

# Second instance of error
# This WILL stop the script
for(i in 1:5){
  print(i)
  complex.array[1][1] <- 5
}
print("This will not be printed because of an error")
```
Here is the output:
```{r}
<simpleError in if (grepl("\n", print.value)) {    print.value <- paste0(sub("\\n.*", "", print.value), "...")}: argument is of length zero>
[1] "Will display simple error before this, so this will print"
[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
Error in if (grepl("\n", print.value)) { : argument is of length zero
[1] "Saving prov.json in /tmp/RtmpzB97ra/prov_rbug"
```

What is interesting is how outside of a control structure, when the error occurs it just prints a `<simpleError>`, but inside of a loop it actually displays an error to the console and stops executing the script. 

I traced the issue to this line in the `.ddg.get.node.val()` function in the DataNodes.R file. It seems with this complex array, when print.value is set there is a problem. 
```{r}
print.value <- Find(function(line) return(startsWith(stringi::stri_trim_left(line),
        "[1,")), print.value)
```

The `Find` function is returning `NULL`. My guess is that nothing is matching the `startsWith` function and the `Find` function by default will return `NULL` if no match is found. `Find(f, x, right = FALSE, nomatch = NULL)`

R Version being used: 3.6.1
rdtLite version: development branch from RDataTracker as of June 10, 2020.

**Comment by blernermhc** [comment]
Fixed in https://github.com/End-to-end-provenance/RDataTracker/commit/560a798c10af73e4c1306f8122c04f63485afb8d
