### ISSUE TITLE
Issue with the grepl

### ISSUE THREAD

**Issue by Ranjanirr** [End-to-end-provenance/RDataTracker#641]
![image](https://user-images.githubusercontent.com/46352350/85349728-38a73900-b4cd-11ea-87a5-ca1f78c6da09.png)
and 
![image](https://user-images.githubusercontent.com/46352350/85349749-4492fb00-b4cd-11ea-9086-cf74f1679245.png)
are errors in the new goal script (which you already have) after running provenance in the console without the previous errors.

**Comment by blernermhc** [comment]
Can you attach the file containing the script?  I am not seeing this error.

**Comment by Ranjanirr** [comment]
You already have the goal script attached in another issue. Please let me know if you need it resent.

**Comment by blernermhc** [comment]
Yes, please resend it. I am not sure I am running the right thing since I cannot duplicate the problem you are seeing.

**Comment by Ranjanirr** [comment]
[Soccer.zip](https://github.com/End-to-end-provenance/RDataTracker/files/4821590/Soccer.zip)

**Comment by blernermhc** [comment]
I am not seeing the grepl message.  Can you download a new version of rdtLite and try again?  Try restarting RStdio, too.

**Comment by Ranjanirr** [comment]
What is the line for downloading the newest version of rdtLite?

Thanks
Ranjani

**Comment by blernermhc** [comment]
```
install_github("End-to-end-provenance/rdtLite", ref="development")
```

**Comment by blernermhc** [comment]
Unable to reproduce.
