### ISSUE TITLE
Provenance directory should be normalized to use Unix-style paths when prov.dir option is used

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#648]
If the prov.dir option is used, the provenance directory is not normalized to use Unix-style paths.  In Windows, for example, the provenance directory may appear as c:\\prov instead of c:/prov in the JSON file.  This could be addressed by adding winslash="/" in line 175 of API_core.R:
     base.dir <- normalizePath(getOption("prov.dir"), winslash=”/”, mustWork=FALSE).

**Comment by blernermhc** [comment]
Implemented in https://github.com/End-to-end-provenance/RDataTracker/commit/1f10c61e99510afd19fe1a3d847c80c3b03681ab
