### ISSUE TITLE
Automatic annotation of tryCatch functions

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#71]
Automatic annotation of tryCatch functions (when a script is run with ddg.run) should be enabled.  tryCatch functions are currently passed over in .ddg.add.function.annotations.

**Comment by blernermhc** [comment]
Do you mean the error handling functions that are passed to tryCatch or the tryCatch call itself?

**Comment by erboose** [comment]
The tryCatch call itself.

**Comment by blernermhc** [comment]
Maybe trace could help us here since this is a function call?  Not really sure how that would help, though.
