### ISSUE TITLE
Automatic annotation of lapply, sapply, and vapply functions

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/RDataTracker#72]
Automatic annotation of lapply, sapply, and vapply functions (when a script is run with ddg.run) should be enabled. These functions are currently passed over in .ddg.add.function.annotations.

**Comment by sckott** [comment]
my simple test of this worked fine, but more testing needed probably, see `HarvardForest/BerkeleyWorkshop/WorkshopGeneratedScripts/lapply_eg.R` file in dropbox

**Comment by blernermhc** [comment]
Works.  If different output is desired, create a new issue and be specific about what you would like to see done differently.
