### ISSUE TITLE
ddg.run error in emacs using ESS

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#78]
R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
 Copyright (C) 2015 The R Foundation for Statistical Computing
 Platform: x86_64-apple-darwin13.4.0 (64-bit)

> ddg.run('Cars.R')
 Error in .External2(C_savehistory, file) : no history available to save

**Comment by MKLau** [comment]
This is an issue with emacs' ESS, which enables user to run an interactive R session within emacs. The issue looks to be that ESS loads an R session that doesn't create a .Rhistory file. That is, it uses "R --no-save" when loading R. Not sure how to fix this, but the key will be having ESS use the "R --save" mode.

**Comment by blernermhc** [comment]
I am not able to reproduce the problem.  When I run in ESS inside Emacs, I see this:
```
> library(RDataTracker)
> ddg.run("TinyCars.R")
[1] "Saving DDG in  /Users/blerner/tmp/ddg_bugs/TinyCars/ddg/ddg.txt"
[1] "Saving DDG in  /Users/blerner/tmp/ddg_bugs/TinyCars/ddg/ddg.json"
Warning message:
In eval(expr, envir, enclos) :
  Shocking! Eight cylinder cars let lower gas mileage!
> 
```
ddg.run does not use the history file so the error message you see confuses me.  Can you try again with the latest version of RDataTracker?

**Comment by MKLau** [comment]
Yep, that works for me now using https://github.com/End-to-end-provenance/RDataTracker/blob/master/R/RDataTracker.R

I had been using the version that's currently on CRAN.
