### ISSUE TITLE
Overwrite option

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#92]
Add an overwrite option to ddg.run.  When off, we should include a timestamp in the ddg directory name.  When on, the timestamp is not included and the ddg directory will get overwritten each time a ddg is created.

**Comment by erboose** [comment]
Suggest default be set to on (overwrite).

**Comment by blernermhc** [comment]
For the timestamp format, we should use the same format as we use for the timestamp recorded at the top of the ddg.txt file.  Here is an example:

2016-06-07T16.20.11EDT

**Comment by alexsiqingliu** [comment]
Added an overwrite parameter to ddg.run, default is TRUE, if user passes overwrite = FALSE then all files will have timestamps

**Comment by blernermhc** [comment]
Fixed in 9b19f02d423c15d0e33bf5bb78ac468f21864385
