### ISSUE TITLE
RMarkdown

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/RDataTracker#96]
Work with rMarkdown files.  Wrap render, rather than source. Or could use purl to extract the R code from a Markdown file. (potentially harder)  Will need to pay attention to knitr options.  May be a hook available to insert ddg.run into the knitr process. 

-- Suggested at OpenSci meeting

**Comment by blernermhc** [comment]
I thought Alex did this but I do not see a relevant pull request.  Someone should test this.

**Comment by MKLau** [comment]
Hey Barbara, the knitr package in R has purl(), which, I think, does the second option of extracting the code chunks.

**Comment by fong22e** [comment]
It has been implemented!
