### ISSUE TITLE
Group project repos under End-to-end-provenance Organization

### ISSUE THREAD

**Issue by MKLau** [End-to-end-provenance/RDataTracker#99]
This would allow for easier management of programmers across projects.

The following link describes how to do this. It's really simple and can easily be undone as well. Something to note immediately, that I really appreciate, is that the issues and the assignments get migrated too, which is awesome!

https://help.github.com/articles/transferring-a-repository/

@blernermhc @erboose

**Comment by blernermhc** [comment]
Both RDataTracker and DDG Explorer have been moved into the End-to-end-provenance organization.
